import { emitDailyContext } from "../../../../shared/grammar-worksheets/daily-build";
import { resolve } from "node:path";
import { syncConversationFlow } from "../../../../shared/conversation-flow/build";
import { grammarUnits } from "../packages/content/src/index";
import { englishSeeds } from "../../../../shared/grammar-worksheets/seeds-en";
import {
  catalogWorksheets,
  emitSharedAssets,
} from "../../../../shared/grammar-worksheets/build";
const worksheets = catalogWorksheets(grammarUnits, englishSeeds, "en");

const root = resolve(import.meta.dir, "..");
const out = resolve(root, "apps/web/public/replacements/en");
// The compatibility page loads classic scripts. Export explicitly to window rather
// than relying on a bundler-specific globalName option or a module loader.
await Bun.write(
  resolve(out, "grammar-worksheets.js"),
  `// Generated by scripts/build-grammar-worksheets.ts.\nwindow.GrammarWorksheets = ${JSON.stringify({ worksheets })};\n`,
);

await emitSharedAssets(out);
await emitDailyContext(root, "en", worksheets);
await syncConversationFlow(root, "en");
console.log(
  `${worksheets.length} English worksheet sets verified against the catalog.`,
);
