import type { WorksheetSeed } from "./seed-builder";

// Four authored contexts per decision: two contrasts and two guided retrieval cues.
const s = (
  topics: string | string[],
  chain: WorksheetSeed["chain"],
  examples: WorksheetSeed["examples"],
  change: string,
  personal: string,
  contextual = false,
): WorksheetSeed[] =>
  (typeof topics === "string" ? [topics] : topics).map((topic) => ({
    topic,
    level: "",
    title: chain[0],
    focusFa:
      "نشانهٔ داده‌شده را پیدا کن؛ فقط شکل هدف را انتخاب کن و دلیلش را بنویس.",
    chain,
    category: chain[1],
    examples,
    change,
    personal,
    contextual,
  }));
export const englishSeeds: readonly WorksheetSeed[] = [
  ...s(
    "Verb be: am/is/are",
    ["am or are?", "subject → form of be", "I am / we are"],
    [
      ["I", "I [[am]] ready.", "are"],
      ["we", "We [[are]] ready.", "am"],
      ["I", "I [[am]] at home.", "are"],
      ["we", "We [[are]] at home.", "am"],
    ],
    "Change I to we.",
    "Write a true sentence about yourself with I am.",
  ),
  ...s(
    "Subject pronouns",
    [
      "Who does the action?",
      "subject position → subject pronoun",
      "she / they",
    ],
    [
      ["Anna", "[[She]] works here.", "Her"],
      ["Anna and Paul", "[[They]] work here.", "Them"],
      ["Paul", "[[He]] lives here.", "Him"],
      ["Paul and Anna", "[[They]] live here.", "Them"],
    ],
    "Refer to Anna and Paul; use the supplied verb work.",
    "Name a person you know, then describe them using a subject pronoun.",
  ),
  ...s(
    "Articles a/an/the",
    ["New or already known?", "reference → article", "a / the"],
    [
      ["first mention of one doctor", "I saw [[a]] doctor.", "the"],
      ["the doctor already mentioned", "I saw [[the]] doctor.", "a"],
      ["first mention of one teacher", "I met [[a]] teacher.", "the"],
      ["the teacher already mentioned", "I met [[the]] teacher.", "a"],
    ],
    "Refer to the doctor already mentioned.",
    "Introduce an object with a or an, then mention it again with the.",
    true,
  ),
  ...s(
    "Plural nouns",
    ["One or more than one?", "number → noun form", "book / books"],
    [
      ["one", "I have one [[book]].", "books"],
      ["two", "I have two [[books]].", "book"],
      ["one", "I have one [[box]].", "boxes"],
      ["three", "I have three [[boxes]].", "box"],
    ],
    "Change one to two.",
    "Write how many books or boxes you have.",
  ),
  ...s(
    "Possessive adjectives",
    [
      "Who owns it?",
      "owner → possessive determiner",
      "Paul → his / Anna → her",
    ],
    [
      ["Paul owns it", "This is [[his]] car.", "her"],
      ["Anna owns it", "This is [[her]] car.", "his"],
      ["Paul owns it", "This is [[his]] book.", "her"],
      ["Anna owns it", "This is [[her]] book.", "his"],
    ],
    "Change the owner from Paul to Anna.",
    "Name someone you know and describe one possession with his or her.",
    true,
  ),
  ...s(
    "Have/has got",
    ["have or has?", "subject → agreement", "I have / she has"],
    [
      ["I", "I [[have]] got a bike.", "has"],
      ["she", "She [[has]] got a bike.", "have"],
      ["I", "I [[have]] got time.", "has"],
      ["he", "He [[has]] got time.", "have"],
    ],
    "Change I to she.",
    "Write about something you have got.",
  ),
  ...s(
    "Present simple affirmative",
    ["Add -s or not?", "third person singular", "I work / she works"],
    [
      ["I", "I [[work]] here.", "works"],
      ["she", "She [[works]] here.", "work"],
      ["we", "We [[live]] here.", "lives"],
      ["he", "He [[lives]] here.", "live"],
    ],
    "Change I to she.",
    "Write about a daily habit using I.",
  ),
  ...s(
    "Present simple negatives",
    [
      "don't or doesn't?",
      "subject → negative auxiliary",
      "I don't / she doesn't",
    ],
    [
      ["I", "I [[don't]] drive.", "doesn't"],
      ["she", "She [[doesn't]] drive.", "don't"],
      ["we", "We [[don't]] work here.", "doesn't"],
      ["he", "He [[doesn't]] work here.", "don't"],
    ],
    "Change I to she.",
    "Write one thing you do not do regularly.",
  ),
  ...s(
    "Present simple questions",
    ["Do or does?", "subject → question auxiliary", "do you / does she"],
    [
      ["you", "[[Do]] you work here?", "Does"],
      ["she", "[[Does]] she work here?", "Do"],
      ["they", "[[Do]] they live nearby?", "Does"],
      ["he", "[[Does]] he live nearby?", "Do"],
    ],
    "Change you to she.",
    "Ask a question about someone's usual routine.",
  ),
  ...s(
    "There is/There are",
    [
      "One thing or several?",
      "following noun → agreement",
      "there is / there are",
    ],
    [
      ["one chair", "There [[is]] a chair.", "are"],
      ["two chairs", "There [[are]] two chairs.", "is"],
      ["one table", "There [[is]] a table.", "are"],
      ["three tables", "There [[are]] three tables.", "is"],
    ],
    "Replace a chair with two chairs.",
    "Describe something in your room with there is or there are.",
  ),
  ...s(
    "Can/can’t",
    ["Which verb form after can?", "modal → base form", "can swim"],
    [
      ["after can", "She can [[swim]].", "swims"],
      ["without can", "She [[swims]].", "swim"],
      ["after can", "He can [[cook]].", "cooks"],
      ["without can", "He [[cooks]].", "cook"],
    ],
    "Remove can and use the third-person present form.",
    "Write a true sentence about what you can do.",
  ),
  ...s(
    "Imperatives",
    ["Do it or don't do it?", "negative imperative", "don't + base verb"],
    [
      ["positive instruction", "[[Open]] the door.", "Opening"],
      ["negative instruction", "[[Don't open]] the door.", "Not open"],
      ["positive instruction", "[[Close]] the window.", "Closing"],
      ["negative instruction", "[[Don't close]] the window.", "Not close"],
    ],
    "Make the instruction negative.",
    "Write a useful positive or negative instruction for your home.",
  ),
  ...s(
    "Prepositions of place",
    ["Inside or on a surface?", "spatial relationship", "in / on"],
    [
      ["inside the box", "The key is [[in]] the box.", "on"],
      ["on its top surface", "The key is [[on]] the box.", "in"],
      ["inside the bag", "The book is [[in]] the bag.", "on"],
      ["on its outer surface", "The book is [[on]] the bag.", "in"],
    ],
    "Put the key on the top surface of the box.",
    "Describe where an object near you is.",
    true,
  ),
  ...s(
    ["Countable and uncountable nouns", "Much/many/a lot of"],
    ["much or many?", "countability", "much water / many books"],
    [
      ["water: uncountable", "How [[much]] water do you need?", "many"],
      ["books: countable plural", "How [[many]] books do you need?", "much"],
      ["time: uncountable", "How [[much]] time do you need?", "many"],
      ["chairs: countable plural", "How [[many]] chairs do you need?", "much"],
    ],
    "Replace water with books.",
    "Ask a question with much or many about something you need.",
  ),
  ...s(
    "Possessive ’s and whose",
    ["Whose possession?", "singular owner → apostrophe + s", "Anna's book"],
    [
      ["Anna owns it", "This is [[Anna's]] book.", "Annas"],
      ["Paul owns it", "This is [[Paul's]] book.", "Pauls"],
      ["Anna owns it", "This is [[Anna's]] car.", "Annas"],
      ["Paul owns it", "This is [[Paul's]] car.", "Pauls"],
    ],
    "Change the owner from Anna to Paul.",
    "Write who owns an object using a name and 's.",
  ),
  ...s(
    "Prepositions of time: at, in, on",
    ["Clock time or day?", "time unit → preposition", "at nine / on Monday"],
    [
      ["clock time", "I start [[at]] nine.", "on"],
      ["weekday", "I start [[on]] Monday.", "at"],
      ["clock time", "We meet [[at]] six.", "on"],
      ["weekday", "We meet [[on]] Friday.", "at"],
    ],
    "Replace nine with Monday.",
    "Say when you start work or study using at.",
  ),
  ...s(
    "Present continuous",
    ["am or is?", "subject → continuous auxiliary", "I am / she is"],
    [
      ["I", "I [[am]] reading.", "is"],
      ["she", "She [[is]] reading.", "am"],
      ["I", "I [[am]] working.", "is"],
      ["he", "He [[is]] working.", "am"],
    ],
    "Change I to she.",
    "Describe what you are doing now.",
  ),
  ...s(
    ["Present simple vs continuous", "Stative and dynamic verbs"],
    [
      "Routine or action now?",
      "time perspective → aspect",
      "work / am working",
    ],
    [
      ["usual routine", "I [[work]] at home every day.", "am working"],
      ["action happening now", "I [[am working]] at home right now.", "work"],
      ["usual routine", "I [[read]] every evening.", "am reading"],
      ["action happening now", "I [[am reading]] right now.", "read"],
    ],
    "Describe an action happening now; replace every day with right now.",
    "Contrast your usual routine with what you are doing now.",
    true,
  ),
  ...s(
    "Past simple regular",
    ["Present or finished past?", "regular verb → -ed", "work / worked"],
    [
      ["routine", "I [[work]] here every day.", "worked"],
      ["finished past", "I [[worked]] here yesterday.", "work"],
      ["routine", "I [[walk]] here every day.", "walked"],
      ["finished past", "I [[walked]] here yesterday.", "walk"],
    ],
    "Move the event to yesterday.",
    "Write about yesterday with a regular past-tense verb.",
    true,
  ),
  ...s(
    "Past simple irregular",
    ["Go in the past", "irregular past form", "go → went"],
    [
      ["routine", "I [[go]] there every day.", "went"],
      ["finished past", "I [[went]] there yesterday.", "goed"],
      ["routine", "We [[go]] home at six.", "goes"],
      ["finished past", "We [[went]] home yesterday.", "goed"],
    ],
    "Move the event to yesterday.",
    "Write where you went yesterday.",
    true,
  ),
  ...s(
    "Past simple questions and negatives",
    ["After did or didn't", "past auxiliary → base form", "did go / didn't go"],
    [
      ["after did", "Did she [[go]]?", "went"],
      ["without did", "She [[went]].", "goed"],
      ["after didn't", "She didn't [[eat]].", "ate"],
      ["without didn't", "She [[ate]].", "eated"],
    ],
    "Turn the question into an affirmative statement without did.",
    "Ask a question with did about a recent event.",
  ),
  ...s(
    ["Future with will", "Future degrees of certainty"],
    ["Certain plan or possibility?", "degree of certainty", "will / might"],
    [
      ["confident prediction", "She [[will]] arrive tomorrow.", "might"],
      ["uncertain possibility", "She [[might]] arrive tomorrow.", "will"],
      ["confident prediction", "It [[will]] rain tonight.", "might"],
      ["uncertain possibility", "It [[might]] rain tonight.", "will"],
    ],
    "Express an uncertain possibility instead of a confident prediction.",
    "Make one prediction about tomorrow and show your certainty.",
    true,
  ),
  ...s(
    "Be going to",
    ["am or are going to?", "subject → form of be", "I am / we are"],
    [
      ["I", "I [[am]] going to study.", "are"],
      ["we", "We [[are]] going to study.", "am"],
      ["I", "I [[am]] going to cook.", "are"],
      ["we", "We [[are]] going to cook.", "am"],
    ],
    "Change I to we.",
    "Write about a plan with going to.",
  ),
  ...s(
    "Comparatives",
    [
      "One comparative marker",
      "short adjective → -er",
      "taller, not two markers",
    ],
    [
      ["tall", "Anna is [[taller]] than Paul.", "more taller"],
      ["short", "Anna is [[shorter]] than Paul.", "more shorter"],
      ["long", "This road is [[longer]] than that one.", "more longer"],
      ["small", "This room is [[smaller]] than that one.", "more smaller"],
    ],
    "Replace tall with short.",
    "Compare two places or objects you know.",
  ),
  ...s(
    "Superlatives",
    ["Which is the highest?", "superlative → the", "the tallest"],
    [
      ["tall", "This is [[the tallest]] building.", "the most tallest"],
      ["small", "This is [[the smallest]] building.", "the most smallest"],
      ["long", "This is [[the longest]] road.", "the most longest"],
      ["short", "This is [[the shortest]] road.", "the most shortest"],
    ],
    "Replace tall with small.",
    "Describe a place you know using a superlative.",
  ),
  ...s(
    "Some/any/no",
    ["Positive or negative context?", "indefinite quantity", "some / any"],
    [
      ["positive statement", "I have [[some]] money.", "any"],
      ["neutral negative statement", "I don't have [[any]] money.", "some"],
      ["positive statement", "We have [[some]] chairs.", "any"],
      ["neutral negative statement", "We don't have [[any]] chairs.", "some"],
    ],
    "Make a neutral negative statement using don't have.",
    "Write a positive and a neutral negative sentence about what you have.",
    true,
  ),
  ...s(
    "Adverbs of frequency",
    ["Before or after the verb?", "main verb or be", "often work / am often"],
    [
      ["ordinary verb", "I [[often work]] here.", "work often"],
      ["be", "I [[am often]] here.", "often am"],
      ["ordinary verb", "She [[often eats]] here.", "eats often"],
      ["be", "She [[is often]] here.", "often is"],
    ],
    "Replace work with am; use neutral adverb position.",
    "Describe a habit using the neutral position of often.",
    true,
  ),
  ...s(
    "Object pronouns",
    ["Subject or object form?", "after the verb → object", "her / him"],
    [
      ["Anna", "I know [[her]].", "she"],
      ["Paul", "I know [[him]].", "he"],
      ["Anna", "I help [[her]].", "she"],
      ["Paul", "I help [[him]].", "he"],
    ],
    "Change the reference from Anna to Paul.",
    "Name someone you know and refer to them with an object pronoun.",
  ),
  ...s(
    "Must/have to",
    [
      "No obligation or prohibition?",
      "negative modal meaning",
      "don't have to / mustn't",
    ],
    [
      ["optional", "You [[don't have to]] come.", "mustn't"],
      ["forbidden", "You [[mustn't]] come.", "don't have to"],
      ["optional", "You [[don't have to]] pay.", "mustn't"],
      ["forbidden", "You [[mustn't]] pay.", "don't have to"],
    ],
    "Change optional permission into a prohibition.",
    "Write about something optional in your routine.",
    true,
  ),
  ...s(
    "Adjectives and prepositions",
    [
      "Which adjective controls the phrase?",
      "adjective → fixed preposition",
      "good at / interested in",
    ],
    [
      ["good", "I am good [[at]] cooking.", "in"],
      ["interested", "I am interested [[in]] cooking.", "at"],
      ["good", "She is good [[at]] drawing.", "in"],
      ["interested", "She is interested [[in]] drawing.", "at"],
    ],
    "Replace good with interested.",
    "Write about an activity you are interested in.",
  ),
  ...s(
    "Adjectives ending in -ed and -ing",
    ["Feeling or cause?", "experiencer or stimulus", "bored / boring"],
    [
      ["Anna's feeling", "Anna is [[bored]].", "boring"],
      ["the film causes boredom", "The film is [[boring]].", "bored"],
      ["Paul's feeling", "Paul is [[interested]].", "interesting"],
      [
        "the book causes interest",
        "The book is [[interesting]].",
        "interested",
      ],
    ],
    "Describe the film as the cause of boredom.",
    "Describe how you feel about a book or activity.",
    true,
  ),
  ...s(
    "Infinitive of purpose",
    ["Why do the action?", "purpose → to + base verb", "to learn"],
    [
      ["learn", "I came [[to learn]].", "for learn"],
      ["help", "I came [[to help]].", "for help you"],
      ["study", "I moved [[to study]].", "for study"],
      ["work", "I moved [[to work]].", "for work there"],
    ],
    "Change the purpose from learning to helping.",
    "Explain why you did something using to + verb.",
  ),
  ...s(
    "Quantifiers: few, a few, little, a little",
    ["Enough to be useful?", "positive or negative quantity", "a few / few"],
    [
      ["some, enough to help", "I have [[a few]] friends here.", "few"],
      ["almost none", "I have [[few]] friends here.", "a few"],
      ["some, enough to help", "I have [[a little]] time.", "little"],
      ["almost none", "I have [[little]] time.", "a little"],
    ],
    "Express almost no friends instead of a useful small number.",
    "Write about a small useful amount of something you have.",
    true,
  ),
  ...s(
    "Present perfect",
    ["has or have?", "subject → perfect auxiliary", "I have / she has"],
    [
      ["I", "I [[have]] finished.", "has"],
      ["she", "She [[has]] finished.", "have"],
      ["we", "We [[have]] arrived.", "has"],
      ["he", "He [[has]] arrived.", "have"],
    ],
    "Change I to she.",
    "Describe something you have finished today.",
  ),
  ...s(
    "Present perfect vs past simple",
    [
      "Finished past time or present result?",
      "time reference → tense",
      "yesterday / so far",
    ],
    [
      ["finished time", "I [[finished]] it yesterday.", "have finished"],
      ["present result, no past date", "I [[have finished]] it now.", "finish"],
      ["finished time", "She [[visited]] twice last year.", "has visited"],
      [
        "unfinished period",
        "She [[has visited]] twice so far this year.",
        "visit",
      ],
    ],
    "Replace yesterday with now and describe the present result.",
    "Write about a finished event yesterday, then a result relevant now.",
  ),
  ...s(
    "For and since",
    [
      "Duration or starting point?",
      "time phrase → for or since",
      "for two years / since 2020",
    ],
    [
      ["duration", "I have lived here [[for]] two years.", "since"],
      ["starting point", "I have lived here [[since]] 2020.", "for"],
      ["duration", "She has waited [[for]] an hour.", "since"],
      ["starting point", "She has waited [[since]] noon.", "for"],
    ],
    "Replace two years with the starting point 2020.",
    "Write how long you have lived or worked somewhere.",
  ),
  ...s(
    "Past continuous",
    ["was or were?", "subject → past be", "I was / we were"],
    [
      ["I", "I [[was]] reading.", "were"],
      ["we", "We [[were]] reading.", "was"],
      ["she", "She [[was]] working.", "were"],
      ["they", "They [[were]] working.", "was"],
    ],
    "Change I to we.",
    "Write what you were doing at a specific time yesterday.",
  ),
  ...s(
    "Past continuous vs past simple",
    [
      "Background or completed event?",
      "past viewpoint → aspect",
      "was reading / arrived",
    ],
    [
      [
        "action already in progress",
        "I [[was reading]] when she arrived.",
        "am reading",
      ],
      ["completed arrival", "She [[arrived]] while I was reading.", "arrive"],
      [
        "action already in progress",
        "I [[was cooking]] when he called.",
        "am cooking",
      ],
      ["completed call", "He [[called]] while I was cooking.", "call"],
    ],
    "Focus on the completed arrival: She … while I was reading.",
    "Describe a background activity interrupted by another event.",
  ),
  ...s(
    "First conditional",
    ["Future condition after if", "if-clause → present form", "if she comes"],
    [
      ["condition", "If she [[comes]], I will wait.", "will come"],
      ["result", "If I wait, she [[will come]].", "will comes"],
      ["condition", "If it [[rains]], I will stay.", "will rain"],
      ["result", "If I stay, she [[will help]].", "will helps"],
    ],
    "Make her coming the result: If I wait, she …",
    "Write one possible future condition and its result.",
  ),
  ...s(
    ["Second conditional", "Counterfactual distance"],
    [
      "Real or imagined condition?",
      "distance → present or past form",
      "if I have / if I had",
    ],
    [
      ["open future possibility", "If I [[have]] time, I will help.", "has"],
      ["imagined present situation", "If I [[had]] time, I would help.", "has"],
      [
        "open future possibility",
        "If she [[knows]], she will tell us.",
        "know",
      ],
      [
        "imagined present situation",
        "If she [[knew]], she would tell us.",
        "know",
      ],
    ],
    "Make the condition imagined; use would help.",
    "Write about an imagined change to your present situation.",
  ),
  ...s(
    "Relative clauses",
    ["Person or thing?", "relative reference", "who / which"],
    [
      ["person", "The person [[who]] called is here.", "which"],
      ["thing", "The phone [[which]] rang is here.", "who"],
      ["person", "The teacher [[who]] helped is here.", "which"],
      ["thing", "The book [[which]] helped is here.", "who"],
    ],
    "Refer to the phone and use rang instead of called.",
    "Describe someone you know using a relative clause.",
  ),
  ...s(
    "Gerunds and infinitives",
    [
      "Which verb controls the next form?",
      "verb complementation",
      "enjoy doing / want to do",
    ],
    [
      ["enjoy", "I enjoy [[reading]].", "to read"],
      ["want", "I want [[to read]].", "reading"],
      ["enjoy", "She enjoys [[cooking]].", "to cook"],
      ["want", "She wants [[to cook]].", "cooking"],
    ],
    "Replace enjoy with want.",
    "Write what you enjoy doing and what you want to do.",
  ),
  ...s(
    "Modal verbs of advice",
    ["Advice or prohibition?", "modal strength", "should / mustn't"],
    [
      ["positive advice", "You [[should]] rest.", "mustn't"],
      ["prohibition", "You [[mustn't]] enter.", "should"],
      ["positive advice", "You [[should]] ask.", "mustn't"],
      ["prohibition", "You [[mustn't]] touch it.", "should"],
    ],
    "Give a prohibition about entering: You … enter.",
    "Give a friend one piece of practical advice.",
    true,
  ),
  ...s(
    "Passive present and past",
    [
      "Present or past passive?",
      "time → form of be",
      "is checked / was checked",
    ],
    [
      ["routine now", "It [[is]] checked every day.", "are"],
      ["finished past", "It [[was]] checked yesterday.", "were"],
      ["routine now", "They [[are]] checked every day.", "is"],
      ["finished past", "They [[were]] checked yesterday.", "was"],
    ],
    "Move the check to yesterday.",
    "Describe something that was repaired or checked recently.",
  ),
  ...s(
    "Reported statements",
    ["Backshift in a past report", "past reporting context", "is → was"],
    [
      ["direct statement now", "She says, “I [[am]] ready.”", "is"],
      ["past report with backshift", "She said she [[was]] ready.", "were"],
      ["direct statement now", "He says, “I [[am]] tired.”", "is"],
      ["past report with backshift", "He said he [[was]] tired.", "were"],
    ],
    "Report her statement with She said she and apply backshift.",
    "Report something a person said yesterday with appropriate backshift.",
  ),
  ...s(
    "Question tags",
    [
      "Positive or negative statement?",
      "tag polarity",
      "is → isn't / isn't → is",
    ],
    [
      ["positive statement", "She is here, [[isn't she]]?", "is she"],
      ["negative statement", "She isn't here, [[is she]]?", "isn't she"],
      ["positive statement", "They are ready, [[aren't they]]?", "are they"],
      ["negative statement", "They aren't ready, [[are they]]?", "aren't they"],
    ],
    "Make the statement negative and use a neutral confirmation tag.",
    "Write a statement about your day with a confirmation tag.",
    true,
  ),
  ...s(
    "Too/enough",
    [
      "Before or after the adjective?",
      "degree-word position",
      "too small / big enough",
    ],
    [
      ["too", "The room is [[too small]].", "small too"],
      ["enough", "The room is [[big enough]].", "enough big"],
      ["too", "The bag is [[too heavy]].", "heavy too"],
      ["enough", "The bag is [[light enough]].", "enough light"],
    ],
    "Use big and enough instead of too and small.",
    "Describe an object using an adjective and enough.",
  ),
  ...s(
    "Capital letters and apostrophes",
    [
      "Possession or contraction?",
      "its / it's",
      "its = possession / it's = it is",
    ],
    [
      ["possession", "The dog moved [[its]] tail.", "it's"],
      ["it is", "[[It's]] a friendly dog.", "Its"],
      ["possession", "The company changed [[its]] name.", "it's"],
      ["it is", "[[It's]] a new company.", "Its"],
    ],
    "Use it is to describe the dog: … a friendly dog.",
    "Write one sentence with its and one with it's.",
  ),
  ...s(
    "Contrasting ideas: although, despite, however",
    [
      "Clause or noun phrase?",
      "concession → complement type",
      "although + clause / despite + noun",
    ],
    [
      ["full clause", "[[Although]] it rained, we went out.", "Despite"],
      ["noun phrase", "[[Despite]] the rain, we went out.", "Although"],
      ["full clause", "[[Although]] it was cold, we stayed.", "Despite"],
      ["noun phrase", "[[Despite]] the cold, we stayed.", "Although"],
    ],
    "Replace it rained with the rain.",
    "Describe doing something despite a difficulty.",
  ),
  ...s(
    "Used to, be used to, get used to",
    [
      "Past habit or familiarity?",
      "used to + base / be used to + -ing",
      "used to drive / used to driving",
    ],
    [
      ["past habit", "I used to [[drive]] here.", "driving"],
      ["familiarity now", "I am used to [[driving]] here.", "drive"],
      ["past habit", "She used to [[work]] late.", "working"],
      ["familiarity now", "She is used to [[working]] late.", "work"],
    ],
    "Describe current familiarity; add am before used to.",
    "Write about something you are now used to doing.",
  ),
  ...s(
    "Intensifiers: so and such",
    [
      "Adjective or noun phrase?",
      "intensifier → phrase type",
      "so helpful / such a helpful person",
    ],
    [
      ["adjective", "She is [[so]] helpful.", "such"],
      ["noun phrase", "She is [[such]] a helpful person.", "so"],
      ["adjective", "It is [[so]] interesting.", "such"],
      ["noun phrase", "It is [[such]] an interesting book.", "so"],
    ],
    "Use the noun phrase a helpful person.",
    "Describe a person or object with so or such.",
  ),
  ...s(
    "Past ability: could, was able to, managed to",
    [
      "General ability or one success?",
      "past ability perspective",
      "could / managed to",
    ],
    [
      ["general childhood ability", "As a child, I [[could]] swim.", "can"],
      [
        "single successful event",
        "Yesterday, I [[managed to]] unlock the door.",
        "manage to",
      ],
      ["general childhood ability", "As a child, she [[could]] read.", "can"],
      [
        "single successful event",
        "Yesterday, she [[managed to]] finish on time.",
        "manage to",
      ],
    ],
    "Describe one successful event yesterday using managed to unlock the door.",
    "Describe a recent success with managed to.",
  ),
  ...s(
    "Past habits: used to, would, past simple",
    [
      "A past state or repeated action?",
      "would for actions in an established past",
      "used to own / would visit",
    ],
    [
      ["past ownership state", "We [[used to own]] a cottage.", "would own"],
      [
        "repeated action in that period",
        "Back then, we [[would visit]] it every summer.",
        "will visit",
      ],
      ["past knowledge state", "She [[used to know]] the owner.", "would know"],
      [
        "repeated action in that period",
        "Back then, she [[would call]] him every week.",
        "will call",
      ],
    ],
    "Describe repeated summer visits in that past period.",
    "Describe one past state with used to and one repeated action.",
    true,
  ),
  ...s(
    ["Phrasal verbs", "Word order in phrasal verbs"],
    ["Noun or object pronoun?", "separable phrasal verb", "turn it off"],
    [
      ["object pronoun", "Please [[turn it off]].", "turn off it"],
      ["noun object", "Please [[turn off the light]].", "turn the off light"],
      ["object pronoun", "Please [[pick it up]].", "pick up it"],
      ["noun object", "Please [[pick up the book]].", "pick the up book"],
    ],
    "Replace it with the light and put the noun after off.",
    "Write an instruction with a separable phrasal verb and an object pronoun.",
  ),
  ...s(
    "Present perfect: just, yet, still, already",
    ["Finished or still unfinished?", "completion marker", "already / yet"],
    [
      ["completed sooner than expected", "I have [[already]] finished.", "yet"],
      ["unfinished up to now", "I haven't finished [[yet]].", "already"],
      ["completed sooner than expected", "She has [[already]] arrived.", "yet"],
      ["unfinished up to now", "She hasn't arrived [[yet]].", "already"],
    ],
    "Say the task is unfinished; use haven't and put yet at the end.",
    "Write about something you have already done or have not done yet.",
    true,
  ),
  ...s(
    "Reflexive pronouns",
    [
      "Is the object the subject?",
      "same reference → reflexive",
      "myself / herself",
    ],
    [
      ["I did it alone", "I taught [[myself]].", "me"],
      ["she did it alone", "She taught [[herself]].", "her"],
      ["I did it alone", "I introduced [[myself]].", "me"],
      ["he did it alone", "He introduced [[himself]].", "him"],
    ],
    "Change I to she.",
    "Write about something you taught yourself.",
    true,
  ),
  ...s(
    "Using as and like",
    [
      "Actual role or similarity?",
      "role → as / comparison → like",
      "as a teacher / like a teacher",
    ],
    [
      ["her actual job", "She works [[as]] a teacher.", "like"],
      ["similar manner, not her job", "She speaks [[like]] a teacher.", "as"],
      ["his actual job", "He works [[as]] a guide.", "like"],
      ["similar manner, not his job", "He speaks [[like]] a guide.", "as"],
    ],
    "Describe similar speech instead of an actual job; use speaks.",
    "Describe your role or compare your manner to another role.",
    true,
  ),
  ...s(
    "Verbs and prepositions",
    ["Wait or depend?", "verb → fixed preposition", "wait for / depend on"],
    [
      ["wait", "I wait [[for]] Anna.", "on"],
      ["depend", "I depend [[on]] Anna.", "for"],
      ["wait", "We wait [[for]] the bus.", "on"],
      ["depend", "We depend [[on]] the bus.", "for"],
    ],
    "Replace wait with depend.",
    "Write what you depend on in your daily life.",
    true,
  ),
  ...s(
    "Present perfect continuous",
    [
      "Activity or completed quantity?",
      "ongoing duration → continuous",
      "have been reading / have read",
    ],
    [
      [
        "ongoing activity",
        "I [[have been reading]] for an hour.",
        "have been read",
      ],
      [
        "completed quantity",
        "I [[have read]] three chapters.",
        "have been read",
      ],
      [
        "ongoing activity",
        "She [[has been writing]] all morning.",
        "has been wrote",
      ],
      [
        "completed quantity",
        "She [[has written]] three pages.",
        "has been written",
      ],
    ],
    "Describe three completed chapters instead of the ongoing hour.",
    "Describe an activity you have been doing recently.",
  ),
  ...s(
    "Past perfect",
    [
      "Before a past reference point?",
      "earlier past → had + participle",
      "had left",
    ],
    [
      ["before the arrival", "When I arrived, she [[had left]].", "has left"],
      ["at the arrival", "When I arrived, she [[left]].", "leave"],
      [
        "before the call",
        "When I called, he [[had finished]].",
        "has finished",
      ],
      ["at the call", "When I called, he [[finished]].", "finish"],
    ],
    "Make her leaving happen at the time of your arrival.",
    "Write about an event completed before another past event.",
  ),
  ...s(
    ["Past perfect continuous", "Advanced tense-aspect choices"],
    [
      "Duration before a past point",
      "past perfect continuous",
      "had been waiting",
    ],
    [
      [
        "duration before arrival",
        "I [[had been waiting]] for an hour when she arrived.",
        "have been waiting",
      ],
      [
        "finished before arrival",
        "I [[had finished]] when she arrived.",
        "have finished",
      ],
      [
        "duration before call",
        "He [[had been working]] for an hour when I called.",
        "has been working",
      ],
      [
        "finished before call",
        "He [[had finished]] when I called.",
        "has finished",
      ],
    ],
    "Describe finishing before her arrival instead of an ongoing wait.",
    "Describe an activity that continued up to a past event.",
  ),
  ...s(
    "Future continuous",
    [
      "Action in progress at a future time",
      "will be + -ing",
      "will be working",
    ],
    [
      ["work", "At noon tomorrow, I will be [[working]].", "work"],
      ["study", "At noon tomorrow, I will be [[studying]].", "study"],
      ["travel", "At six tomorrow, she will be [[travelling]].", "travel"],
      ["cook", "At six tomorrow, she will be [[cooking]].", "cook"],
    ],
    "Replace working with studying.",
    "Say what you will be doing at a specific time tomorrow.",
  ),
  ...s(
    "Future perfect",
    [
      "Completed by a future deadline",
      "will have + participle",
      "will have finished",
    ],
    [
      ["finish", "By Friday, I will have [[finished]].", "finish"],
      ["leave", "By Friday, I will have [[left]].", "leave"],
      ["arrive", "By noon, she will have [[arrived]].", "arrive"],
      ["eat", "By noon, she will have [[eaten]].", "eat"],
    ],
    "Replace finish with leave.",
    "Describe something you expect to have completed by next month.",
  ),
  ...s(
    "Third conditional",
    ["An unreal past condition", "if → had + participle", "if I had known"],
    [
      ["know", "If I [[had known]], I would have helped.", "would have known"],
      ["hear", "If I [[had heard]], I would have helped.", "would have heard"],
      ["see", "If she [[had seen]], she would have called.", "would have seen"],
      [
        "know",
        "If she [[had known]], she would have called.",
        "would have known",
      ],
    ],
    "Replace known with heard.",
    "Describe an unreal past condition and its imagined past result.",
  ),
  ...s(
    "Mixed conditionals",
    [
      "Present or past result?",
      "result time → conditional form",
      "would be / would have been",
    ],
    [
      [
        "present result",
        "If I had rested, I [[would be ready now]].",
        "would have been ready yesterday",
      ],
      [
        "past result",
        "If I had rested, I [[would have been ready yesterday]].",
        "would be ready now",
      ],
      [
        "present result",
        "If she had trained, she [[would be stronger now]].",
        "would have been stronger then",
      ],
      [
        "past result",
        "If she had trained, she [[would have been stronger then]].",
        "would be stronger now",
      ],
    ],
    "Move the result from now to yesterday.",
    "Link an unreal past choice to an imagined present result.",
    true,
  ),
  ...s(
    [
      "Modal deduction present",
      "Modals and expressions of probability",
      "Nuanced modality",
    ],
    ["Strong deduction or possibility?", "epistemic strength", "must / might"],
    [
      ["strong deduction from evidence", "She [[must]] be at home.", "might"],
      ["uncertain possibility", "She [[might]] be at home.", "must"],
      [
        "strong deduction from evidence",
        "He [[must]] know the answer.",
        "might",
      ],
      ["uncertain possibility", "He [[might]] know the answer.", "must"],
    ],
    "Express an uncertain possibility instead of a strong deduction.",
    "Draw one deduction from evidence and state how certain you are.",
    true,
  ),
  ...s(
    "Modal deduction past",
    [
      "Deduction about a past event",
      "modal + have + participle",
      "must have left",
    ],
    [
      ["strong deduction", "She [[must have left]].", "must has left"],
      ["uncertain possibility", "She [[might have left]].", "might has left"],
      ["strong deduction", "He [[must have forgotten]].", "must has forgotten"],
      [
        "uncertain possibility",
        "He [[might have forgotten]].",
        "might has forgotten",
      ],
    ],
    "Reduce the certainty using might.",
    "Make a deduction about a recent event with must have or might have.",
  ),
  ...s(
    "Causative have/get",
    [
      "Do it yourself or arrange a service?",
      "have + object + past participle",
      "have it repaired",
    ],
    [
      ["arranged service", "I [[had my bike repaired]].", "had my bike repair"],
      ["own action", "I [[repaired my bike]].", "repaired my bike repaired"],
      [
        "arranged service",
        "She [[had her window cleaned]].",
        "had her window clean",
      ],
      [
        "own action",
        "She [[cleaned her window]].",
        "cleaned her window cleaned",
      ],
    ],
    "Say you repaired the bike yourself.",
    "Describe a service you had done recently.",
  ),
  ...s(
    ["Advanced passive", "Advanced passives review"],
    ["Passive after a modal", "modal + be + participle", "must be checked"],
    [
      ["necessity", "The report must [[be checked]].", "be check"],
      ["possibility", "The report can [[be checked]].", "be check"],
      ["necessity", "The form must [[be signed]].", "be sign"],
      ["possibility", "The form can [[be signed]].", "be sign"],
    ],
    "Change must to can to express possibility.",
    "Write about something that must be checked or completed.",
  ),
  ...s(
    "Participle clauses",
    [
      "Who performs the opening action?",
      "shared subject",
      "Walking home, Anna …",
    ],
    [
      ["Anna walks", "Walking home, [[Anna called me]].", "the phone rang"],
      ["Anna waits", "Waiting outside, [[Anna called me]].", "the phone rang"],
      [
        "Paul reads",
        "Reading the report, [[Paul took notes]].",
        "the answer became clear",
      ],
      [
        "Paul checks",
        "Checking the figures, [[Paul took notes]].",
        "the error appeared",
      ],
    ],
    "Replace Walking home with Waiting outside.",
    "Describe two of your own actions using a participle clause with a clear subject.",
    true,
  ),
  ...s(
    ["Wish and if only", "Unreal time"],
    [
      "Present wish or past regret?",
      "wish → past or past perfect",
      "knew / had known",
    ],
    [
      ["wish about now", "I wish I [[knew]] the answer now.", "know"],
      [
        "regret about then",
        "I wish I [[had known]] the answer then.",
        "have known",
      ],
      ["wish about now", "She wishes she [[had]] more time now.", "has"],
      [
        "regret about then",
        "She wishes she [[had had]] more time then.",
        "has had",
      ],
    ],
    "Move the wish from now to a regret about then.",
    "Write one present wish or past regret.",
  ),
  ...s(
    "Inversion after negative adverbials",
    [
      "Negative phrase first",
      "fronting → auxiliary inversion",
      "Never have I …",
    ],
    [
      ["never first", "Never [[have I seen]] this before.", "I have seen"],
      [
        "neutral order",
        "[[I have never seen]] this before.",
        "I never have seen",
      ],
      ["rarely first", "Rarely [[have we heard]] such news.", "we have heard"],
      [
        "neutral order",
        "[[We have rarely heard]] such news.",
        "We rarely have heard",
      ],
    ],
    "Use neutral subject-first order and move never before seen.",
    "Emphasise an unusual experience using never or rarely at the start.",
    true,
  ),
  ...s(
    "Gradable and non-gradable adjectives",
    [
      "Degree or extreme meaning?",
      "intensifier compatibility",
      "very tired / absolutely exhausted",
    ],
    [
      ["gradable adjective", "I am [[very]] tired.", "absolutely"],
      ["extreme adjective", "I am [[absolutely]] exhausted.", "very"],
      ["gradable adjective", "It is [[very]] cold.", "absolutely"],
      ["extreme adjective", "It is [[absolutely]] freezing.", "very"],
    ],
    "Replace tired with the extreme adjective exhausted.",
    "Describe how you feel with a suitable adjective and intensifier.",
    true,
  ),
  ...s(
    "British and American grammar",
    [
      "Choose a consistent standard",
      "past participle of get",
      "BrE got / AmE gotten",
    ],
    [
      ["British English: become", "She has [[got]] better.", "gotten"],
      ["American English: become", "She has [[gotten]] better.", "got"],
      ["British English: become", "It has [[got]] colder.", "gotten"],
      ["American English: become", "It has [[gotten]] colder.", "got"],
    ],
    "Use the common American participle for become.",
    "Describe a recent change using one consistent English variety.",
    true,
  ),
  ...s(
    "Modifying comparatives",
    ["How much difference?", "comparative modifier", "much / a little"],
    [
      ["large difference", "This room is [[much]] larger.", "very"],
      ["small difference", "This room is [[a little]] larger.", "very"],
      ["large difference", "This route is [[much]] shorter.", "very"],
      ["small difference", "This route is [[a little]] shorter.", "very"],
    ],
    "Make the difference small instead of large.",
    "Compare two places and specify the size of the difference.",
  ),
  ...s(
    "Reported speech: questions",
    [
      "Direct or embedded question?",
      "embedded clause → statement order",
      "where she lives",
    ],
    [
      [
        "embedded question",
        "I asked [[where she lived]].",
        "where did she live",
      ],
      [
        "direct question",
        "I asked, “[[Where does she live]]?”",
        "Where she lives",
      ],
      [
        "embedded question",
        "He asked [[when it started]].",
        "when did it start",
      ],
      [
        "direct question",
        "He asked, “[[When does it start]]?”",
        "When it starts",
      ],
    ],
    "Use a direct present-time question after I asked and keep quotation marks.",
    "Report a question you asked recently.",
  ),
  ...s(
    "Gerund or infinitive: change in meaning",
    [
      "Recall an event or fulfil a duty?",
      "remember + -ing / to-infinitive",
      "remember locking / remember to lock",
    ],
    [
      [
        "memory of a past action",
        "I remember [[locking]] the door.",
        "to lock",
      ],
      ["do not forget a duty", "I remember [[to lock]] the door.", "locking"],
      [
        "memory of a past action",
        "She remembers [[sending]] the email.",
        "to send",
      ],
      [
        "do not forget a duty",
        "She remembers [[to send]] the email.",
        "sending",
      ],
    ],
    "Describe remembering to fulfil the duty, rather than remembering the past action.",
    "Write about a duty you remember to do.",
    true,
  ),
  ...s(
    "Cleft sentences",
    [
      "Which element is the focus?",
      "it-cleft → highlighted constituent",
      "It was Anna who …",
    ],
    [
      [
        "focus on Anna",
        "It was [[Anna who called yesterday]].",
        "yesterday that Anna called",
      ],
      [
        "focus on yesterday",
        "It was [[yesterday that Anna called]].",
        "Anna who called yesterday",
      ],
      [
        "focus on Paul",
        "It was [[Paul who helped today]].",
        "today that Paul helped",
      ],
      [
        "focus on today",
        "It was [[today that Paul helped]].",
        "Paul who helped today",
      ],
    ],
    "Move the focus from Anna to yesterday.",
    "Correct a possible misunderstanding about your day using an it-cleft.",
    true,
  ),
  ...s(
    "Inversion in conditionals",
    [
      "A condition without if",
      "had / were / should before subject",
      "Had I known, …",
    ],
    [
      ["without if", "[[Had I known]], I would have helped.", "I had known"],
      ["with if", "[[If I had known]], I would have helped.", "If had I known"],
      [
        "without if",
        "[[Had she called]], I would have answered.",
        "She had called",
      ],
      [
        "with if",
        "[[If she had called]], I would have answered.",
        "If had she called",
      ],
    ],
    "Add if and restore subject-first clause order.",
    "Write an unreal past condition without if.",
  ),
  ...s(
    ["Nominalisation", "Compressed academic structures"],
    [
      "Action as a clause or noun?",
      "nominalisation → noun phrase",
      "analyse / analysis",
    ],
    [
      ["verb", "We [[analysed]] the data.", "analysis"],
      ["noun", "The [[analysis]] of the data took time.", "analysed"],
      ["verb", "We [[revised]] the plan.", "revision"],
      ["noun", "The [[revision]] of the plan took time.", "revised"],
    ],
    "Use the noun analysis in The … of the data took time.",
    "Describe a task once as a clause and once as a noun phrase.",
  ),
  ...s(
    "Hedging and stance",
    [
      "How strong is the evidence?",
      "claim strength",
      "may suggest / demonstrates",
    ],
    [
      [
        "tentative interpretation",
        "The result [[may suggest]] a link.",
        "definitively proves",
      ],
      [
        "observed association",
        "The result [[shows]] a link.",
        "might possibly suggest",
      ],
      [
        "tentative interpretation",
        "The evidence [[may suggest]] a difference.",
        "definitively proves",
      ],
      [
        "observed difference",
        "The evidence [[shows]] a difference.",
        "might possibly suggest",
      ],
    ],
    "State an observed association without claiming causation.",
    "Write a tentative interpretation of a pattern you have observed.",
    true,
  ),
  ...s(
    ["Advanced discourse markers", "Advanced cohesion"],
    [
      "Consequence or concession?",
      "logical relationship",
      "therefore / nevertheless",
    ],
    [
      [
        "consequence",
        "It was unsafe. [[Therefore]], we stopped.",
        "Nevertheless",
      ],
      [
        "despite the obstacle",
        "It was unsafe. [[Nevertheless]], we continued.",
        "Therefore",
      ],
      ["consequence", "It was late. [[Therefore]], we left.", "Nevertheless"],
      [
        "despite the obstacle",
        "It was late. [[Nevertheless]], we stayed.",
        "Therefore",
      ],
    ],
    "Describe continuing despite the obstacle.",
    "Connect two statements from your life with a precise logical marker.",
    true,
  ),
  ...s(
    "Substitution and ellipsis",
    [
      "Avoid repeating the verb phrase",
      "auxiliary substitution",
      "she does / they do",
    ],
    [
      ["positive agreement", "I like tea, and she [[does too]].", "do too"],
      [
        "negative agreement",
        "I don't like tea, and she [[doesn't either]].",
        "don't either",
      ],
      ["positive agreement", "We work here, and they [[do too]].", "does too"],
      [
        "negative agreement",
        "We don't work here, and they [[don't either]].",
        "doesn't either",
      ],
    ],
    "Make both statements negative.",
    "Compare your preference with someone else's using auxiliary substitution.",
  ),
  ...s(
    "Complex relative clauses",
    [
      "Person or thing after a preposition?",
      "formal relative pronoun",
      "to whom / in which",
    ],
    [
      ["person", "This is the person to [[whom]] I wrote.", "which"],
      ["thing", "This is the report in [[which]] it appears.", "whom"],
      ["person", "This is the colleague with [[whom]] I worked.", "which"],
      ["thing", "This is the office in [[which]] I worked.", "whom"],
    ],
    "Use the supplied frame This is the report in … it appears.",
    "Describe a person or place with a formal preposition + relative pronoun.",
  ),
  ...s(
    "Advanced reporting verbs",
    [
      "Which pattern follows the reporting verb?",
      "verb complementation",
      "admit doing / agree to do",
    ],
    [
      ["admit", "She admitted [[making]] a mistake.", "to make"],
      ["agree", "She agreed [[to make]] a change.", "making"],
      ["admit", "He admitted [[taking]] the money.", "to take"],
      ["agree", "He agreed [[to take]] the test.", "taking"],
    ],
    "Use agreed and replace a mistake with a change.",
    "Report something you agreed to do or admitted doing.",
  ),
  ...s(
    ["Emphasis with auxiliaries", "Rhetorical grammar"],
    [
      "Emphasise a positive statement",
      "do / does + base form",
      "do agree / does agree",
    ],
    [
      ["I", "I [[do agree]] with you.", "do agrees"],
      ["she", "She [[does agree]] with you.", "does agrees"],
      ["we", "We [[do need]] help.", "do needs"],
      ["he", "He [[does need]] help.", "does needs"],
    ],
    "Change I to she and preserve the emphasis.",
    "Emphasise a sincere opinion with do or does.",
  ),
  ...s(
    ["Fronting", "Marked word order"],
    [
      "Bring the object into focus",
      "object fronting → keep subject before verb",
      "This book, I recommend",
    ],
    [
      [
        "fronted object",
        "[[This book, I recommend]].",
        "This book, recommend I",
      ],
      ["neutral order", "[[I recommend this book]].", "I this book recommend"],
      ["fronted object", "[[That idea, we support]].", "That idea, support we"],
      ["neutral order", "[[We support that idea]].", "We that idea support"],
    ],
    "Return to neutral subject-first order.",
    "Front an object to contrast it with another option.",
  ),
  ...s(
    "Complex noun phrases",
    [
      "Which noun does the modifier describe?",
      "modifier attachment",
      "new report / new study",
    ],
    [
      [
        "the report is new",
        "I read [[the new report on the study]].",
        "the report on the new study",
      ],
      [
        "the study is new",
        "I read [[the report on the new study]].",
        "the new report on the study",
      ],
      [
        "the review is detailed",
        "I read [[the detailed review of the book]].",
        "the review of the detailed book",
      ],
      [
        "the book is detailed",
        "I read [[the review of the detailed book]].",
        "the detailed review of the book",
      ],
    ],
    "Make new describe the study instead of the report.",
    "Describe a document with one clearly attached modifier.",
    true,
  ),
  ...s(
    ["Register control", "Style shifting", "Genre-specific grammar"],
    [
      "Request or direct instruction?",
      "audience → register",
      "Could you …? / Please …",
    ],
    [
      [
        "polite request",
        "[[Could you send me the report, please?]]",
        "Send me that thing now!",
      ],
      [
        "clear work instruction",
        "[[Please send me the report.]]",
        "Chuck that thing over here!",
      ],
      [
        "polite request",
        "[[Could you close the window, please?]]",
        "Shut that thing now!",
      ],
      ["clear work instruction", "[[Please close the window.]]", "Shut it!"],
    ],
    "Turn the request into a clear work instruction beginning Please.",
    "Write a polite request you could actually use at work or in a course.",
    true,
  ),
  ...s(
    "Parallelism",
    [
      "Keep coordinated forms parallel",
      "matched phrase structure",
      "reading and writing",
    ],
    [
      [
        "two -ing forms",
        "I enjoy [[reading and writing]].",
        "reading and to write",
      ],
      [
        "two to-infinitives",
        "I want [[to read and to write]].",
        "to read and writing",
      ],
      [
        "two -ing forms",
        "She enjoys [[planning and organising]].",
        "planning and to organise",
      ],
      [
        "two to-infinitives",
        "She wants [[to plan and to organise]].",
        "to plan and organising",
      ],
    ],
    "Replace enjoy with want and use parallel to-infinitives.",
    "State two related goals in a parallel structure.",
  ),
  ...s(
    "Layered subordination",
    [
      "A question inside a report",
      "embedded question → subject before verb",
      "whether she knows where …",
    ],
    [
      [
        "location question",
        "I asked whether she knew [[where he lived]].",
        "where did he live",
      ],
      [
        "time question",
        "I asked whether she knew [[when he arrived]].",
        "when did he arrive",
      ],
      [
        "location question",
        "He asked whether I knew [[where she worked]].",
        "where did she work",
      ],
      [
        "time question",
        "He asked whether I knew [[when she finished]].",
        "when did she finish",
      ],
    ],
    "Replace the location question with when he arrived.",
    "Embed a question inside a report while keeping each clause clear.",
  ),
  ...s(
    "Idiomatic clause patterns",
    [
      "The sooner, the better",
      "paired comparative clauses",
      "the more …, the easier …",
    ],
    [
      ["more practice", "The [[more]] I practise, the easier it gets.", "most"],
      [
        "less practice",
        "The [[less]] I practise, the harder it gets.",
        "least",
      ],
      [
        "longer wait",
        "The [[longer]] I wait, the more tired I get.",
        "longest",
      ],
      [
        "earlier start",
        "The [[earlier]] I start, the sooner I finish.",
        "earliest",
      ],
    ],
    "Use less practice and a harder result.",
    "Describe a relationship in your own learning with paired comparatives.",
  ),
  ...s(
    "Ambiguity control",
    [
      "Make the intended reference explicit",
      "ambiguous pronoun → repeated name",
      "Anna / Maria",
    ],
    [
      ["Anna is ready", "Anna told Maria that [[Anna]] was ready.", "she"],
      ["Maria is ready", "Anna told Maria that [[Maria]] was ready.", "she"],
      ["Paul is leaving", "Paul told Tim that [[Paul]] was leaving.", "he"],
      ["Tim is leaving", "Paul told Tim that [[Tim]] was leaving.", "he"],
    ],
    "Make Maria the person who is ready.",
    "Write about two people and remove any ambiguous pronoun reference.",
    true,
  ),
  ...s(
    "Advanced punctuation and grammar",
    ["Two independent clauses", "semicolon or comma + conjunction", "; / , so"],
    [
      ["semicolon connection", "It was late[[;]] we left.", ","],
      ["explicit consequence", "It was late[[, so]] we left.", ","],
      ["semicolon connection", "It was cold[[;]] we went inside.", ","],
      ["explicit consequence", "It was cold[[, so]] we went inside.", ","],
    ],
    "Use a comma and so to state the consequence explicitly.",
    "Connect two independent clauses about your day with a semicolon.",
  ),
  ...s(
    "Editing for naturalness",
    [
      "Choose the conventional word partner",
      "collocation",
      "make a decision / do research",
    ],
    [
      ["decision", "We [[made]] a decision.", "did"],
      ["research", "We [[did]] some research.", "made"],
      ["decision", "She [[made]] a decision.", "did"],
      ["research", "She [[did]] some research.", "made"],
    ],
    "Replace a decision with some research.",
    "Write about a decision or research task using its natural verb partner.",
  ),
  ...s(
    "Integrated automatic production",
    [
      "Clarify one detail while speaking",
      "self-repair → more precisely",
      "general detail → specific detail",
    ],
    [
      [
        "time precision",
        "I'll come in the morning, [[more precisely at nine]].",
        "more precisely in the morning",
      ],
      [
        "place precision",
        "I'll wait outside, [[more precisely by the entrance]].",
        "more precisely outside",
      ],
      [
        "time precision",
        "We'll meet in the evening, [[more precisely at seven]].",
        "more precisely in the evening",
      ],
      [
        "place precision",
        "We'll meet in the park, [[more precisely by the gate]].",
        "more precisely in the park",
      ],
    ],
    "Clarify the place instead: I'll wait outside, …",
    "Say a real plan aloud and clarify one detail without restarting the sentence.",
    true,
  ),
];
