import type { WorksheetSeed } from "./seed-builder";

// Topic aliases are explicit curriculum links, not guesses from title keywords.
// Related topics may practise the same narrow decision; all other grammar is supplied.
const s = (
  topics: string | string[],
  chain: WorksheetSeed["chain"],
  examples: WorksheetSeed["examples"],
  change: string,
  personal: string,
  contextual = false,
): WorksheetSeed[] =>
  (typeof topics === "string" ? [topics] : topics).map((topic) => ({
    topic,
    level: "",
    title: chain[0],
    focusFa:
      "نشانهٔ داده‌شده را پیدا کن؛ فقط شکل هدف را انتخاب کن و دلیلش را بنویس.",
    chain,
    category: chain[1],
    examples,
    change,
    personal,
    contextual,
  }));
export const germanSeeds: readonly WorksheetSeed[] = [
  ...s(
    "Perfekt mit haben",
    ["habe oder hast?", "Subjekt → Hilfsverb", "ich habe / du hast"],
    [
      ["ich", "Ich [[habe]] gekocht.", "hast"],
      ["du", "Du [[hast]] gekocht.", "habe"],
      ["ich", "Ich [[habe]] gelernt.", "hast"],
      ["du", "Du [[hast]] gelernt.", "habe"],
    ],
    "Ändere ich zu du.",
    "Schreibe mit ich habe, was du gestern gemacht hast.",
  ),
  ...s(
    "Perfekt mit sein",
    ["bin oder bist?", "Subjekt → Hilfsverb", "ich bin / du bist"],
    [
      ["ich", "Ich [[bin]] angekommen.", "bist"],
      ["du", "Du [[bist]] angekommen.", "bin"],
      ["ich", "Ich [[bin]] geblieben.", "bist"],
      ["du", "Du [[bist]] geblieben.", "bin"],
    ],
    "Ändere ich zu du.",
    "Schreibe, wann du gestern zu Hause angekommen bist.",
  ),
  ...s(
    ["Präteritum von sein/haben/Modalverben", "Präteritum in Erzählungen"],
    ["war oder hatte?", "Zustand oder Besitz", "war müde / hatte Zeit"],
    [
      ["Zustand", "Ich [[war]] müde.", "hatte"],
      ["Besitz", "Ich [[hatte]] Zeit.", "war"],
      ["Zustand", "Ich [[war]] krank.", "hatte"],
      ["Besitz", "Ich [[hatte]] Geld.", "war"],
    ],
    "Beschreibe mit Zeit einen Besitz statt mit müde einen Zustand.",
    "Schreibe mit war über deinen gestrigen Zustand.",
  ),
  ...s(
    "Dativ",
    ["helfen oder sehen?", "Verb → Objektkasus", "helfen → dem / sehen → den"],
    [
      ["helfen", "Ich helfe [[dem]] Mann.", "den"],
      ["sehen", "Ich sehe [[den]] Mann.", "dem"],
      ["helfen", "Ich helfe [[dem]] Lehrer.", "den"],
      ["sehen", "Ich sehe [[den]] Lehrer.", "dem"],
    ],
    "Ersetze helfe durch sehe.",
    "Schreibe, wem du oft hilfst.",
  ),
  ...s(
    "Wechselpräpositionen",
    ["Ort oder Ziel?", "in → Dativ oder Akkusativ", "im Zimmer / ins Zimmer"],
    [
      ["Aufenthaltsort", "Ich bin [[im]] Zimmer.", "ins"],
      ["Ziel", "Ich gehe [[ins]] Zimmer.", "im"],
      ["Aufenthaltsort", "Ich bin [[im]] Büro.", "ins"],
      ["Ziel", "Ich gehe [[ins]] Büro.", "im"],
    ],
    "Beschreibe mit gehe das Ziel statt mit bin den Ort.",
    "Schreibe, in welchem Zimmer du gerade bist.",
  ),
  ...s(
    "Modalverben müssen, dürfen, sollen, wollen",
    ["Pflicht oder Erlaubnis?", "Modalbedeutung", "muss / darf"],
    [
      ["Pflicht", "Ich [[muss]] heute arbeiten.", "darf"],
      ["Erlaubnis", "Ich [[darf]] heute arbeiten.", "muss"],
      ["Pflicht", "Ich [[muss]] hier warten.", "darf"],
      ["Erlaubnis", "Ich [[darf]] hier warten.", "muss"],
    ],
    "Drücke Erlaubnis statt Pflicht aus.",
    "Schreibe über eine Pflicht in deinem Alltag.",
    true,
  ),
  ...s(
    "Komparativ und Superlativ",
    ["Zwei oder alle vergleichen?", "Vergleichsgrad", "größer / am größten"],
    [
      [
        "zwei Räume",
        "Dieser Raum ist [[größer]] als der andere.",
        "am größten",
      ],
      ["alle Räume", "Dieser Raum ist [[am größten]].", "am größer"],
      [
        "zwei Wege",
        "Dieser Weg ist [[kürzer]] als der andere.",
        "am kürzesten",
      ],
      ["alle Wege", "Dieser Weg ist [[am kürzesten]].", "am kürzer"],
    ],
    "Vergleiche den Raum mit allen Räumen; entferne als der andere.",
    "Vergleiche zwei Orte, die du kennst, mit größer.",
  ),
  ...s(
    "Nebensatz mit weil",
    ["weil → Verb wohin?", "Verbendstellung", "weil ich Zeit habe"],
    [
      ["habe ans Ende", "Ich komme, weil [[ich Zeit habe]].", "ich habe Zeit"],
      ["bin ans Ende", "Ich komme, weil [[ich frei bin]].", "ich bin frei"],
      [
        "habe ans Ende",
        "Ich bleibe, weil [[ich Urlaub habe]].",
        "ich habe Urlaub",
      ],
      ["bin ans Ende", "Ich bleibe, weil [[ich müde bin]].", "ich bin müde"],
    ],
    "Ersetze Zeit haben durch frei sein im weil-Satz.",
    "Begründe mit weil eine heutige Entscheidung.",
  ),
  ...s(
    "Nebensatz mit dass",
    ["dass → Verb ans Ende", "Verbendstellung", "dass er kommt"],
    [
      ["kommen", "Ich hoffe, dass [[er kommt]].", "kommt er"],
      ["bleiben", "Ich hoffe, dass [[er bleibt]].", "bleibt er"],
      ["helfen", "Ich hoffe, dass [[sie hilft]].", "hilft sie"],
      ["zuhören", "Ich hoffe, dass [[sie zuhört]].", "zuhört sie"],
    ],
    "Ersetze kommt durch bleibt.",
    "Schreibe mit ich hoffe, dass über morgen.",
  ),
  ...s(
    "wenn und als",
    [
      "Einmal oder wiederholt?",
      "Vergangenheit → Zeitkonnektor",
      "einmal → als / wiederholt → wenn",
    ],
    [
      ["einmal gestern", "[[Als]] ich gestern ankam, war es still.", "Wenn"],
      ["jedes Mal früher", "[[Wenn]] ich früher ankam, war es still.", "Als"],
      [
        "einmal letzte Woche",
        "[[Als]] ich letzte Woche anrief, war er da.",
        "Wenn",
      ],
      ["jedes Mal früher", "[[Wenn]] ich früher anrief, war er da.", "Als"],
    ],
    "Beschreibe mit früher eine wiederholte Situation statt einmal gestern.",
    "Schreibe mit als über ein einmaliges vergangenes Erlebnis.",
    true,
  ),
  ...s(
    "Reflexive Verben",
    ["mich oder dich?", "Subjekt → Reflexivpronomen", "ich → mich / du → dich"],
    [
      ["ich", "Ich freue [[mich]].", "dich"],
      ["du", "Du freust [[dich]].", "mich"],
      ["ich", "Ich beeile [[mich]].", "dich"],
      ["du", "Du beeilst [[dich]].", "mich"],
    ],
    "Ändere ich zu du; verwende freust.",
    "Schreibe, worauf du dich freust.",
  ),
  ...s(
    "Adjektiv nach sein",
    ["Adjektiv nach sein?", "prädikativ → keine Endung", "ist ruhig"],
    [
      ["nach ist", "Der Raum ist [[ruhig]].", "ruhige"],
      ["nach ist", "Die Straße ist [[ruhig]].", "ruhige"],
      ["nach ist", "Der Kaffee ist [[heiß]].", "heiße"],
      ["nach ist", "Die Suppe ist [[heiß]].", "heißer"],
    ],
    "Ersetze der Raum durch die Straße; behalte das Adjektiv bei.",
    "Beschreibe mit ist einen Ort in deiner Nähe.",
  ),
  ...s(
    [
      "Zeitangaben und Wortstellung",
      "Informationsstruktur durch Vorfeldbesetzung",
      "Informationsstruktur und Vorfeld",
      "Thema-Rhema-Gliederung",
      "Markierte Wortstellung",
    ],
    [
      "Was steht im Vorfeld?",
      "Hauptsatz → Verb an Position 2",
      "Heute arbeite ich …",
    ],
    [
      ["Zeit zuerst", "[[Heute arbeite ich]] zu Hause.", "Heute ich arbeite"],
      ["Person zuerst", "[[Ich arbeite heute]] zu Hause.", "Ich heute arbeite"],
      ["Zeit zuerst", "[[Morgen lerne ich]] zu Hause.", "Morgen ich lerne"],
      ["Person zuerst", "[[Ich lerne morgen]] zu Hause.", "Ich morgen lerne"],
    ],
    "Beginne mit ich statt mit heute.",
    "Schreibe einen Satz über deinen Alltag mit einer Zeitangabe im Vorfeld.",
  ),
  ...s(
    "Indefinitpronomen man/jemand/niemand",
    ["Eine Person oder keine?", "unbestimmter Bezug", "jemand / niemand"],
    [
      ["mindestens eine Person", "Hier wartet [[jemand]].", "niemand"],
      ["keine Person", "Hier wartet [[niemand]].", "jemand"],
      ["mindestens eine Person", "Heute kommt [[jemand]].", "niemand"],
      ["keine Person", "Heute kommt [[niemand]].", "jemand"],
    ],
    "Drücke aus, dass keine Person wartet.",
    "Schreibe mit jemand oder niemand über einen heutigen Besuch.",
    true,
  ),
  ...s(
    [
      "Adjektivdeklination nach Artikeln",
      "Adjektivdeklination Grundlagen",
      "Adjektivdeklination vollständig",
    ],
    [
      "der oder ein vor dem Adjektiv?",
      "Maskulinum im Nominativ",
      "der gute / ein guter",
    ],
    [
      ["der", "Hier ist der [[gute]] Kaffee.", "guter"],
      ["ein", "Das ist ein [[guter]] Kaffee.", "gute"],
      ["der", "Hier ist der [[neue]] Tisch.", "neuer"],
      ["ein", "Das ist ein [[neuer]] Tisch.", "neue"],
    ],
    "Schreibe mit Das ist ein statt Hier ist der.",
    "Beschreibe einen Gegenstand mit ein guter oder ein neuer.",
  ),
  ...s(
    ["Relativsätze mit der, die und das", "Relativsätze Nominativ/Akkusativ"],
    [
      "Handelt die Bezugsperson?",
      "Relativpronomen → Satzrolle",
      "der kommt / den ich sehe",
    ],
    [
      ["Mann ist Subjekt", "Das ist der Mann, [[der]] hier wohnt.", "den"],
      ["Mann ist Objekt", "Das ist der Mann, [[den]] ich sehe.", "der"],
      [
        "Lehrer ist Subjekt",
        "Das ist der Lehrer, [[der]] hier arbeitet.",
        "den",
      ],
      ["Lehrer ist Objekt", "Das ist der Lehrer, [[den]] ich kenne.", "der"],
    ],
    "Ersetze hier wohnt durch ich sehe; der Mann ist jetzt Objekt.",
    "Beschreibe einen Mann mit einem Relativsatz, in dem er Subjekt ist.",
  ),
  ...s(
    ["Nebensätze mit ob", "indirekte Fragen"],
    ["Wortfrage oder Ja/Nein-Frage?", "indirekte Frage einleiten", "wann / ob"],
    [
      ["Ja/Nein-Frage", "Ich frage, [[ob]] er kommt.", "dass"],
      ["Zeit erfragen", "Ich frage, [[wann]] er kommt.", "dass"],
      ["Ja/Nein-Frage", "Ich frage, [[ob]] sie anruft.", "dass"],
      ["Zeit erfragen", "Ich frage, [[wann]] sie anruft.", "dass"],
    ],
    "Frage jetzt nach der Zeit seines Kommens.",
    "Schreibe mit ich weiß nicht, ob über einen morgigen Plan.",
  ),
  ...s(
    "darum, deshalb und deswegen",
    ["deshalb im Vorfeld", "Verb direkt danach", "deshalb bleibe ich"],
    [
      ["bleiben", "Deshalb [[bleibe ich]] hier.", "ich bleibe"],
      ["warten", "Deshalb [[warte ich]] hier.", "ich warte"],
      ["lernen", "Deshalb [[lerne ich]] heute.", "ich lerne"],
      ["arbeiten", "Deshalb [[arbeite ich]] heute.", "ich arbeite"],
    ],
    "Ersetze bleibe durch warte.",
    "Nenne einen Grund und formuliere danach die Folge mit deshalb.",
  ),
  ...s(
    "denn und sondern",
    ["Begründen oder berichtigen?", "logische Beziehung", "denn / sondern"],
    [
      ["Grund", "Ich bleibe, [[denn]] ich bin müde.", "sondern"],
      ["Berichtigung", "Ich fahre nicht, [[sondern]] ich bleibe.", "denn"],
      ["Grund", "Ich lerne, [[denn]] ich habe Zeit.", "sondern"],
      ["Berichtigung", "Ich schlafe nicht, [[sondern]] ich lerne.", "denn"],
    ],
    "Berichtige eine Verneinung: Ich fahre nicht, … ich bleibe.",
    "Berichtige mit nicht … sondern eine Aussage über dich.",
    true,
  ),
  ...s(
    "Verben mit Dativ und Akkusativ",
    [
      "Empfänger oder Sache?",
      "geben → Dativ und Akkusativ",
      "dem Mann / den Schlüssel",
    ],
    [
      ["Empfänger", "Ich gebe [[dem]] Mann das Buch.", "den"],
      ["Sache", "Ich gebe Anna [[den]] Schlüssel.", "dem"],
      ["Empfänger", "Ich zeige [[dem]] Lehrer das Bild.", "den"],
      ["Sache", "Ich zeige Anna [[den]] Garten.", "dem"],
    ],
    "Gib jetzt Anna den Schlüssel: Ich gebe Anna … Schlüssel.",
    "Schreibe, wem du zuletzt etwas gegeben hast.",
  ),
  ...s(
    [
      "Verben mit Präpositionen Grundlagen",
      "Verben mit Präpositionen",
      "Komplexe Verbvalenz und Rektion",
    ],
    [
      "warten oder teilnehmen?",
      "Verb → feste Präposition",
      "warten auf / teilnehmen an",
    ],
    [
      ["warten", "Ich warte [[auf]] den Kurs.", "an"],
      ["teilnehmen", "Ich nehme [[an]] dem Kurs teil.", "auf"],
      ["warten", "Wir warten [[auf]] das Treffen.", "an"],
      ["teilnehmen", "Wir nehmen [[an]] dem Treffen teil.", "auf"],
    ],
    "Ersetze warten durch teilnehmen; dem Kurs und teil sind vorgegeben.",
    "Schreibe, worauf du gerade wartest.",
  ),
  ...s(
    ["Futur I mit werden", "Futur I für Prognosen und Vermutungen"],
    ["werde oder wirst?", "Subjekt → werden", "ich werde / du wirst"],
    [
      ["ich", "Ich [[werde]] kommen.", "wirst"],
      ["du", "Du [[wirst]] kommen.", "werde"],
      ["ich", "Ich [[werde]] warten.", "wirst"],
      ["du", "Du [[wirst]] warten.", "werde"],
    ],
    "Ändere ich zu du.",
    "Formuliere mit werde eine Prognose über deine kommende Woche.",
  ),
  ...s(
    ["da- und wo-Komposita Grundlagen", "Pronominaladverbien"],
    ["Person oder Sache?", "Präpositionalbezug", "auf ihn / darauf"],
    [
      ["Bezug: Paul", "Ich warte [[auf ihn]].", "darauf"],
      ["Bezug: das Ergebnis", "Ich warte [[darauf]].", "auf ihn"],
      ["Bezug: Anna", "Ich denke [[an sie]].", "daran"],
      ["Bezug: das Treffen", "Ich denke [[daran]].", "an sie"],
    ],
    "Beziehe dich jetzt auf das Ergebnis statt auf Paul.",
    "Nenne eine Sache, auf die du wartest, und beziehe dich danach mit darauf darauf.",
    true,
  ),
  ...s(
    ["Infinitiv mit zu Grundlagen", "Infinitiv mit zu"],
    ["Wo steht zu?", "einfaches oder trennbares Verb", "zu lernen / anzurufen"],
    [
      ["lernen", "Ich versuche, [[zu lernen]].", "lernen zu"],
      ["anrufen", "Ich versuche, [[anzurufen]].", "zu anrufen"],
      ["arbeiten", "Ich versuche, [[zu arbeiten]].", "arbeiten zu"],
      ["aufstehen", "Ich versuche, früh [[aufzustehen]].", "zu aufstehen"],
    ],
    "Ersetze lernen durch anrufen.",
    "Schreibe mit ich versuche, was du regelmäßig üben möchtest.",
  ),
  ...s(
    ["Plusquamperfekt", "Tempusfolge in Berichten"],
    [
      "Vor einem vergangenen Ereignis?",
      "Vorzeitigkeit → Plusquamperfekt",
      "hatte gelernt",
    ],
    [
      ["vor der Prüfung gestern", "Ich [[hatte]] vorher gelernt.", "habe"],
      ["bis jetzt", "Ich [[habe]] heute gelernt.", "hatte"],
      ["vor dem Besuch gestern", "Ich [[hatte]] vorher gekocht.", "habe"],
      ["bis jetzt", "Ich [[habe]] heute gekocht.", "hatte"],
    ],
    "Verlege den Bezug in die Gegenwart und ersetze vorher durch heute.",
    "Schreibe, was du vor einem vergangenen Termin schon erledigt hattest.",
    true,
  ),
  ...s(
    "Relativsätze Dativ",
    [
      "helfen oder sehen im Relativsatz?",
      "Verb → Kasus des Relativpronomens",
      "dem / den",
    ],
    [
      ["helfen", "Das ist der Mann, [[dem]] ich helfe.", "den"],
      ["sehen", "Das ist der Mann, [[den]] ich sehe.", "dem"],
      ["helfen", "Das ist der Lehrer, [[dem]] ich helfe.", "den"],
      ["sehen", "Das ist der Lehrer, [[den]] ich sehe.", "dem"],
    ],
    "Ersetze helfe durch sehe.",
    "Beschreibe eine Person, der du hilfst, mit einem Relativsatz.",
  ),
  ...s(
    "Konjunktiv II mit würde",
    ["würde + welche Verbform?", "würde → Infinitiv", "würde reisen"],
    [
      ["würde", "Ich würde gern [[reisen]].", "reise"],
      ["ohne würde", "Ich [[reise]] gern.", "reisen"],
      ["würde", "Ich würde gern [[helfen]].", "helfe"],
      ["ohne würde", "Ich [[helfe]] gern.", "helfen"],
    ],
    "Entferne würde und konjugiere reisen für ich.",
    "Schreibe mit würde gern über einen Wunsch.",
  ),
  ...s(
    "Konjunktiv II von sein/haben/Modalverben",
    [
      "Wirklich oder gewünscht?",
      "Indikativ oder Konjunktiv II",
      "habe / hätte",
    ],
    [
      ["wirklicher Besitz", "Ich [[habe]] mehr Zeit.", "hätte"],
      ["Wunsch", "Ich [[hätte]] gern mehr Zeit.", "habe"],
      ["wirklicher Besitz", "Ich [[habe]] Urlaub.", "hätte"],
      ["Wunsch", "Ich [[hätte]] gern Urlaub.", "habe"],
    ],
    "Formuliere einen Wunsch; ergänze gern.",
    "Schreibe mit hätte gern über einen Wunsch.",
    true,
  ),
  ...s(
    "Passiv Präsens",
    [
      "Eine Sache oder mehrere?",
      "Passiv → Kongruenz von werden",
      "wird / werden",
    ],
    [
      ["Singular", "Der Brief [[wird]] geprüft.", "werden"],
      ["Plural", "Die Briefe [[werden]] geprüft.", "wird"],
      ["Singular", "Der Antrag [[wird]] geprüft.", "werden"],
      ["Plural", "Die Anträge [[werden]] geprüft.", "wird"],
    ],
    "Setze der Brief in den vorgegebenen Plural die Briefe.",
    "Schreibe, was an deinem Arbeitsplatz regelmäßig geprüft wird.",
  ),
  ...s(
    "Passiv Präteritum und Perfekt",
    ["Passiv im Perfekt?", "geworden oder worden", "ist geprüft worden"],
    [
      ["Passiv", "Der Brief ist geprüft [[worden]].", "geworden"],
      ["Zustandsänderung", "Der Brief ist nass [[geworden]].", "worden"],
      ["Passiv", "Der Antrag ist geprüft [[worden]].", "geworden"],
      ["Zustandsänderung", "Der Antrag ist wichtig [[geworden]].", "worden"],
    ],
    "Beschreibe nass werden statt geprüft werden.",
    "Schreibe, was bei dir kürzlich repariert worden ist.",
  ),
  ...s(
    "um...zu / damit",
    [
      "Wer handelt im Zielsatz?",
      "gleiches oder anderes Subjekt",
      "um zu / damit",
    ],
    [
      [
        "ich handle in beiden Teilen",
        "Ich lerne, [[um die Prüfung zu bestehen]].",
        "um ich die Prüfung bestehe",
      ],
      [
        "du handelst im Zielsatz",
        "Ich helfe dir, [[damit du die Prüfung bestehst]].",
        "um du die Prüfung bestehst",
      ],
      [
        "ich handle in beiden Teilen",
        "Ich spare, [[um ein Fahrrad zu kaufen]].",
        "um ich ein Fahrrad kaufe",
      ],
      [
        "du handelst im Zielsatz",
        "Ich gebe dir Geld, [[damit du ein Fahrrad kaufst]].",
        "um du ein Fahrrad kaufst",
      ],
    ],
    "Formuliere: Ich helfe dir. Du sollst die Prüfung bestehen. Verbinde mit damit.",
    "Nenne ein persönliches Ziel mit um … zu.",
  ),
  ...s(
    [
      "obwohl/trotzdem",
      "Konzessive und adversative Strukturen",
      "Konnektoren und Satzverknüpfung",
    ],
    [
      "obwohl oder trotzdem?",
      "Neben- oder Hauptsatz",
      "obwohl … ist / trotzdem bleibt …",
    ],
    [
      ["Nebensatz", "[[Obwohl]] es spät ist, bleibe ich.", "Trotzdem"],
      ["Hauptsatz", "Es ist spät. [[Trotzdem]] bleibe ich.", "Obwohl"],
      ["Nebensatz", "[[Obwohl]] es regnet, gehe ich.", "Trotzdem"],
      ["Hauptsatz", "Es regnet. [[Trotzdem]] gehe ich.", "Obwohl"],
    ],
    "Bilde zwei Hauptsätze; beginne mit Es ist spät.",
    "Beschreibe mit obwohl eine Handlung trotz eines Hindernisses.",
  ),
  ...s(
    "Genitivgrundlagen",
    ["Wessen Buch?", "maskuliner Genitiv Singular", "des Mannes"],
    [
      ["der Mann", "Das ist das Buch [[des Mannes]].", "der Mann"],
      ["die Frau", "Das ist das Buch [[der Frau]].", "die Frau"],
      ["der Lehrer", "Das ist das Büro [[des Lehrers]].", "der Lehrer"],
      ["die Lehrerin", "Das ist das Büro [[der Lehrerin]].", "die Lehrerin"],
    ],
    "Ändere den Besitzer von der Mann zu die Frau.",
    "Beschreibe mit dem Genitiv, wem ein Gegenstand gehört.",
  ),
  ...s(
    ["Vorgangspassiv und Zustandspassiv", "Zustandspassiv"],
    [
      "Vorgang oder Ergebnis?",
      "werden oder sein",
      "wird geöffnet / ist geöffnet",
    ],
    [
      ["Öffnung geschieht gerade", "Die Tür [[wird]] geöffnet.", "ist"],
      ["Tür steht bereits offen", "Die Tür [[ist]] geöffnet.", "wird"],
      [
        "Schließung geschieht gerade",
        "Das Fenster [[wird]] geschlossen.",
        "ist",
      ],
      ["Fenster ist bereits zu", "Das Fenster [[ist]] geschlossen.", "wird"],
    ],
    "Beschreibe das fertige Ergebnis statt des laufenden Vorgangs.",
    "Beschreibe mit ist geöffnet oder ist geschlossen eine Tür bei dir.",
    true,
  ),
  ...s(
    ["Temporalsätze mit bevor, nachdem und seitdem", "Komplexe Temporalsätze"],
    ["Welche Handlung kommt zuerst?", "Zeitrelation", "bevor / nachdem"],
    [
      ["erst essen, dann gehen", "Ich esse, [[bevor]] ich gehe.", "nachdem"],
      [
        "erst gehen, dann essen",
        "Ich esse, [[nachdem]] ich gegangen bin.",
        "bevor",
      ],
      [
        "erst lesen, dann schreiben",
        "Ich lese, [[bevor]] ich schreibe.",
        "nachdem",
      ],
      [
        "erst schreiben, dann lesen",
        "Ich lese, [[nachdem]] ich geschrieben habe.",
        "bevor",
      ],
    ],
    "Kehre die Reihenfolge um: Erst gehen, dann essen. Verwende ich gegangen bin.",
    "Beschreibe zwei Tätigkeiten in deinem Tagesablauf mit bevor.",
    true,
  ),
  ...s(
    "ohne zu und anstatt zu",
    ["Unterlassung oder Ersatz?", "Infinitivkonnektor", "ohne zu / anstatt zu"],
    [
      [
        "keine Begleithandlung",
        "Ich gehe, [[ohne]] mich zu verabschieden.",
        "anstatt",
      ],
      [
        "Ersatz für Verabschieden",
        "Ich winke, [[anstatt]] mich zu verabschieden.",
        "ohne",
      ],
      ["keine Begleithandlung", "Ich esse, [[ohne]] zu sprechen.", "anstatt"],
      ["Ersatz für Sprechen", "Ich schreibe, [[anstatt]] zu sprechen.", "ohne"],
    ],
    "Beschreibe Winken als Ersatz für das Verabschieden: Ich winke, …",
    "Schreibe mit ohne zu über eine unterlassene Begleithandlung.",
    true,
  ),
  ...s(
    "lassen als Vollverb und Hilfsverb",
    ["lassen + Infinitiv", "Veranlassung → ohne zu", "reparieren lassen"],
    [
      ["Veranlassung", "Ich lasse das Rad [[reparieren]].", "zu reparieren"],
      ["Absicht", "Ich plane, das Rad [[zu reparieren]].", "reparieren"],
      ["Veranlassung", "Ich lasse das Fenster [[putzen]].", "zu putzen"],
      ["Absicht", "Ich plane, das Fenster [[zu putzen]].", "putzen"],
    ],
    "Formuliere mit Ich plane eine eigene Absicht statt einer Veranlassung.",
    "Schreibe, was du gelegentlich reparieren lässt.",
  ),
  ...s(
    "brauchen nicht zu",
    ["Keine Pflicht", "brauchen nicht → zu + Infinitiv", "nicht zu warten"],
    [
      ["brauchen", "Du brauchst nicht [[zu warten]].", "warten zu"],
      ["müssen", "Du musst nicht [[warten]].", "zu warten"],
      ["brauchen", "Du brauchst nicht [[zu kommen]].", "kommen zu"],
      ["müssen", "Du musst nicht [[kommen]].", "zu kommen"],
    ],
    "Ersetze brauchst durch musst.",
    "Schreibe, was du heute nicht zu erledigen brauchst.",
  ),
  ...s(
    ["Zweiteilige Konnektoren", "sowohl...als auch / weder...noch"],
    [
      "Beides oder keines?",
      "Konnektorpaar",
      "sowohl … als auch / weder … noch",
    ],
    [
      [
        "beide Tätigkeiten",
        "Ich kann [[sowohl lesen als auch schreiben]].",
        "sowohl lesen noch schreiben",
      ],
      [
        "keine der Tätigkeiten",
        "Ich kann [[weder lesen noch schreiben]].",
        "weder lesen als auch schreiben",
      ],
      [
        "beide Tätigkeiten",
        "Ich kann [[sowohl kochen als auch backen]].",
        "sowohl kochen noch backen",
      ],
      [
        "keine der Tätigkeiten",
        "Ich kann [[weder kochen noch backen]].",
        "weder kochen als auch backen",
      ],
    ],
    "Verneine beide Fähigkeiten mit weder … noch.",
    "Nenne zwei Fähigkeiten mit sowohl … als auch.",
  ),
  ...s(
    ["Genitivpräpositionen", "Erweiterte Genitivpräpositionen"],
    [
      "wegen + welcher Kasus?",
      "geschriebener Standard → Genitiv",
      "wegen des Regens",
    ],
    [
      ["wegen + der Regen", "Ich bleibe wegen [[des Regens]].", "den Regen"],
      ["wegen + die Kälte", "Ich bleibe wegen [[der Kälte]].", "die Kälte"],
      ["trotz + der Regen", "Ich gehe trotz [[des Regens]].", "den Regen"],
      ["trotz + die Kälte", "Ich gehe trotz [[der Kälte]].", "die Kälte"],
    ],
    "Ersetze der Regen durch die Kälte.",
    "Begründe eine Entscheidung mit wegen und einem Genitiv.",
  ),
  ...s(
    "Konjunktiv II Vergangenheit",
    [
      "Vergangener irrealer Wunsch",
      "hätte oder wäre?",
      "hätte gelernt / wäre gekommen",
    ],
    [
      ["lernen → haben", "Ich [[hätte]] gern gelernt.", "wäre"],
      ["kommen → sein", "Ich [[wäre]] gern gekommen.", "hätte"],
      ["arbeiten → haben", "Ich [[hätte]] gern gearbeitet.", "wäre"],
      ["bleiben → sein", "Ich [[wäre]] gern geblieben.", "hätte"],
    ],
    "Ersetze gelernt durch gekommen.",
    "Schreibe, was du gestern gern anders gemacht hättest.",
  ),
  ...s(
    "Passiv mit Modalverben",
    ["Modalverb im Passiv", "Partizip + werden", "muss geprüft werden"],
    [
      ["Passiv", "Der Brief muss [[geprüft werden]].", "prüfen werden"],
      ["Aktiv", "Anna muss den Brief [[prüfen]].", "geprüft"],
      ["Passiv", "Der Antrag muss [[geprüft werden]].", "prüfen werden"],
      ["Aktiv", "Anna muss den Antrag [[prüfen]].", "geprüft"],
    ],
    "Wechsle zur vorgegebenen Aktivform: Anna muss den Brief …",
    "Schreibe, was bei dir bald erledigt werden muss.",
  ),
  ...s(
    ["Nominalisierung", "Verbalisierung und Nominalisierung abwägen"],
    [
      "Handlung als Nomen?",
      "Nominalisierung → Großschreibung",
      "lesen / das Lesen",
    ],
    [
      ["Verb", "Ich möchte [[lesen]].", "Lesen"],
      ["nominalisierter Infinitiv", "Das [[Lesen]] hilft mir.", "lesen"],
      ["Verb", "Ich möchte [[schreiben]].", "Schreiben"],
      [
        "nominalisierter Infinitiv",
        "Das [[Schreiben]] hilft mir.",
        "schreiben",
      ],
    ],
    "Formuliere mit Das … hilft mir; verwende lesen als Nomen.",
    "Schreibe mit das Lernen über deinen Alltag.",
  ),
  ...s(
    "N-Deklination",
    ["der Student als Objekt", "schwaches Nomen → -en", "den Studenten"],
    [
      ["Nominativ", "Der [[Student]] kommt.", "Studenten"],
      ["Akkusativ", "Ich sehe den [[Studenten]].", "Student"],
      ["Nominativ", "Der [[Kollege]] kommt.", "Kollegen"],
      ["Akkusativ", "Ich sehe den [[Kollegen]].", "Kollege"],
    ],
    "Verwende den Studenten als Objekt: Ich sehe den …",
    "Schreibe einen Satz über einen Studenten oder Kollegen als Objekt.",
  ),
  ...s(
    ["Partizipien als Adjektive", "Partizipialattribute erweitern"],
    ["Handelnd oder betroffen?", "Partizip I oder II", "prüfende / geprüfte"],
    [
      ["Person prüft", "Die [[prüfende]] Person ist hier.", "geprüfte"],
      ["Person wurde geprüft", "Die [[geprüfte]] Person ist hier.", "prüfende"],
      ["Person fragt", "Die [[fragende]] Person wartet.", "gefragte"],
      ["Person wurde gefragt", "Die [[gefragte]] Person wartet.", "fragende"],
    ],
    "Beschreibe die Person als betroffen statt als handelnd.",
    "Beschreibe eine handelnde Person mit einem Partizip-I-Attribut.",
    true,
  ),
  ...s(
    "je...desto/umso",
    [
      "je → welcher Partner?",
      "proportionaler Vergleich",
      "je mehr, desto besser",
    ],
    [
      ["je", "Je mehr ich übe, [[desto]] sicherer werde ich.", "als"],
      ["ohne je", "Ich werde sicherer, [[wenn]] ich mehr übe.", "desto"],
      ["je", "Je länger ich warte, [[desto]] müder werde ich.", "als"],
      ["ohne je", "Ich werde müder, [[wenn]] ich länger warte.", "desto"],
    ],
    "Formuliere mit wenn: Ich werde sicherer, … ich mehr übe.",
    "Beschreibe einen Zusammenhang aus deinem Alltag mit je … desto.",
  ),
  ...s(
    "erweiterte Relativsätze",
    ["Person oder ganze Aussage?", "Relativbezug", "der / was"],
    [
      ["ganze Aussage", "Paul kommt, [[was]] mich freut.", "der"],
      ["Person Paul", "Paul, [[der]] heute kommt, hilft mir.", "was"],
      ["ganze Aussage", "Anna bleibt, [[was]] mich freut.", "die"],
      ["Person Anna", "Anna, [[die]] heute bleibt, hilft mir.", "was"],
    ],
    "Beziehe dich auf Paul: Paul, … heute kommt, hilft mir.",
    "Kommentiere eine ganze Aussage mit was mich freut.",
  ),
  ...s(
    [
      "indirekte Rede Grundlagen",
      "Indirekte Rede mit Konjunktiv I",
      "Konjunktiv I vollständig",
      "Indirekte Rede mit Tempus und Modalität",
    ],
    [
      "Eigene Aussage oder Bericht?",
      "Indikativ oder Konjunktiv I",
      "ist / sei",
    ],
    [
      ["eigene Feststellung", "Er [[ist]] müde.", "sei"],
      ["distanzierter Bericht", "Er sagt, er [[sei]] müde.", "ist"],
      ["eigene Feststellung", "Sie [[ist]] bereit.", "sei"],
      ["distanzierter Bericht", "Sie sagt, sie [[sei]] bereit.", "ist"],
    ],
    "Berichte distanziert mit Er sagt, er …",
    "Gib eine Aussage einer bekannten Person mit sei wieder.",
    true,
  ),
  ...s(
    [
      "Nomen-Verb-Verbindungen / Funktionsverbgefüge",
      "Funktionsverbgefüge systematisch",
      "Idiomatizität und Kollokation",
    ],
    [
      "Eine Entscheidung …?",
      "feste Nomen-Verb-Verbindung",
      "Entscheidung treffen / Frage stellen",
    ],
    [
      ["Entscheidung", "Wir [[treffen]] eine Entscheidung.", "machen"],
      ["Frage", "Wir [[stellen]] eine Frage.", "machen"],
      ["Entscheidung", "Sie [[trifft]] eine Entscheidung.", "macht"],
      ["Frage", "Sie [[stellt]] eine Frage.", "macht"],
    ],
    "Ersetze eine Entscheidung durch eine Frage.",
    "Schreibe über eine Entscheidung, die du bald triffst.",
  ),
  ...s(
    "Wortstellung im Mittelfeld",
    ["Zwei Objektpronomen", "Akkusativ vor Dativ", "es ihm"],
    [
      ["zwei Pronomen", "Ich gebe [[es ihm]].", "ihm es"],
      ["zwei Nomen", "Ich gebe [[dem Mann das Buch]].", "dem das Mann Buch"],
      ["zwei Pronomen", "Ich zeige [[es ihr]].", "ihr es"],
      ["zwei Nomen", "Ich zeige [[der Frau das Bild]].", "der das Frau Bild"],
    ],
    "Ersetze es durch das Buch und ihm durch dem Mann; verwende die neutrale Reihenfolge.",
    "Nenne eine Sache und eine Person; schreibe dann einen Satz mit zwei Objektpronomen.",
  ),
  ...s(
    ["Modalpartikeln im Gespräch", "Diskurspartikeln und Registersteuerung"],
    ["Gemeinsam bekannt oder offen?", "Modalpartikel doch", "du weißt doch …"],
    [
      [
        "an gemeinsames Wissen erinnern",
        "Du weißt [[doch]], wo ich wohne.",
        "vielleicht",
      ],
      [
        "Unsicherheit ausdrücken",
        "Du weißt [[vielleicht]], wo ich wohne.",
        "doch",
      ],
      [
        "an gemeinsames Wissen erinnern",
        "Du kennst [[doch]] den Weg.",
        "vielleicht",
      ],
      ["Unsicherheit ausdrücken", "Du kennst [[vielleicht]] den Weg.", "doch"],
    ],
    "Drücke Unsicherheit statt gemeinsamen Wissens aus.",
    "Erinnere eine vertraute Person mit doch an gemeinsames Wissen.",
    true,
  ),
  ...s(
    "Konzessive Verknüpfung mit dennoch und gleichwohl",
    ["Hindernis oder Folge?", "konzessiv oder konsekutiv", "dennoch / deshalb"],
    [
      [
        "Handlung trotz Hindernis",
        "Es regnet. [[Dennoch]] gehe ich spazieren.",
        "Deshalb",
      ],
      [
        "Handlung als Folge",
        "Es regnet. [[Deshalb]] bleibe ich zu Hause.",
        "Dennoch",
      ],
      [
        "Handlung trotz Hindernis",
        "Es ist spät. [[Dennoch]] lerne ich weiter.",
        "Deshalb",
      ],
      [
        "Handlung als Folge",
        "Es ist spät. [[Deshalb]] gehe ich schlafen.",
        "Dennoch",
      ],
    ],
    "Beschreibe eine Folge: Es regnet. … bleibe ich zu Hause.",
    "Beschreibe eine Handlung trotz eines Hindernisses mit dennoch.",
    true,
  ),
  ...s(
    [
      "Kausale und konsekutive Verknüpfung",
      "Kausale Zuschreibung und wissenschaftliche Positionierung",
    ],
    ["Grund oder Folge?", "weil oder sodass", "Grund → weil / Folge → sodass"],
    [
      ["Grund", "Ich bleibe, [[weil]] es regnet.", "sodass"],
      ["Folge", "Es regnet, [[sodass]] ich bleibe.", "weil"],
      ["Grund", "Ich gehe, [[weil]] der Kurs endet.", "sodass"],
      ["Folge", "Der Kurs endet, [[sodass]] ich gehe.", "weil"],
    ],
    "Beginne mit Es regnet und formuliere danach die Folge.",
    "Begründe eine eigene Entscheidung mit weil.",
    true,
  ),
  ...s(
    "Nominalisierte Adjektive",
    ["Adjektiv ohne Nomen", "Nominalisierung → Großschreibung", "etwas Neues"],
    [
      ["ohne Nomen", "Ich lerne etwas [[Neues]].", "neues"],
      ["vor einem Nomen", "Ich lerne ein [[neues]] Wort.", "Neues"],
      ["ohne Nomen", "Ich suche etwas [[Gutes]].", "gutes"],
      ["vor einem Nomen", "Ich suche ein [[gutes]] Buch.", "Gutes"],
    ],
    "Verwende neues vor dem vorgegebenen Nomen Wort: Ich lerne ein … Wort.",
    "Schreibe mit etwas Neues über eine Lernerfahrung.",
  ),
  ...s(
    ["Subjektive Bedeutung der Modalverben", "Modalität und Evidentialität"],
    [
      "Schlussfolgerung oder fremde Quelle?",
      "epistemisches Modalverb",
      "muss / soll",
    ],
    [
      [
        "eigene sichere Schlussfolgerung",
        "Sie [[muss]] zu Hause sein.",
        "soll",
      ],
      ["unbestätigte fremde Angabe", "Sie [[soll]] zu Hause sein.", "muss"],
      [
        "eigene sichere Schlussfolgerung",
        "Er [[muss]] die Lösung kennen.",
        "soll",
      ],
      ["unbestätigte fremde Angabe", "Er [[soll]] die Lösung kennen.", "muss"],
    ],
    "Kennzeichne die Aussage als unbestätigte fremde Angabe.",
    "Formuliere eine vorsichtige fremde Angabe mit soll und nenne ihre Quelle.",
    true,
  ),
  ...s(
    "Ersatzformen des Passivs",
    ["Möglichkeit ausdrücken", "sich lassen + Infinitiv", "lässt sich lösen"],
    [
      ["Möglichkeit", "Die Aufgabe [[lässt sich lösen]].", "lässt sich gelöst"],
      ["Notwendigkeit", "Die Aufgabe [[ist zu lösen]].", "ist zu gelöst"],
      ["Möglichkeit", "Der Text [[lässt sich kürzen]].", "lässt sich gekürzt"],
      ["Notwendigkeit", "Der Text [[ist zu kürzen]].", "ist zu gekürzt"],
    ],
    "Drücke eine Notwendigkeit mit ist zu aus.",
    "Beschreibe mit lässt sich eine lösbare Aufgabe.",
  ),
  ...s(
    [
      "Komplexe Nominalgruppen",
      "Stilistische Verdichtung",
      "Informationsdichte kontrollieren",
    ],
    [
      "Attribut eindeutig zuordnen",
      "Anschluss an das Bezugsnomen",
      "Bericht über die Studie",
    ],
    [
      [
        "Studie wurde veröffentlicht",
        "Der Bericht über [[die gestern veröffentlichte Studie]] liegt vor.",
        "die Studie des gestern veröffentlichten Berichts",
      ],
      [
        "Bericht wurde veröffentlicht",
        "[[Der gestern veröffentlichte Bericht]] über die Studie liegt vor.",
        "Der Bericht über die gestern veröffentlichte Studie",
      ],
      [
        "Studie ist neu",
        "Die Kritik an [[der neuen Studie]] ist präzise.",
        "der Studie der neuen Kritik",
      ],
      [
        "Kritik ist neu",
        "[[Die neue Kritik]] an der Studie ist präzise.",
        "Die Kritik an der neuen Studie",
      ],
    ],
    "Ordne gestern veröffentlicht dem Bericht statt der Studie zu.",
    "Beschreibe einen Text und ordne ihm genau ein Attribut eindeutig zu.",
    true,
  ),
  ...s(
    ["Partizipialkonstruktionen", "Infinitiv- und Partizipialverdichtung"],
    [
      "Wer handelt in der Partizipialgruppe?",
      "gemeinsames Subjekt",
      "Lächelnd kam Anna …",
    ],
    [
      ["Anna lächelt", "Lächelnd [[kam Anna herein]].", "öffnete sich die Tür"],
      [
        "Anna öffnet die Tür",
        "Die Tür öffnend, [[kam Anna herein]].",
        "fiel das Licht ins Zimmer",
      ],
      ["Paul wartet", "Auf den Bus wartend, [[las Paul]].", "verging die Zeit"],
      [
        "Paul liest",
        "Den Bericht lesend, [[machte Paul Notizen]].",
        "kam die Lösung in Sicht",
      ],
    ],
    "Ersetze Lächelnd durch Die Tür öffnend und setze ein Komma.",
    "Beschreibe eine eigene Handlung mit einer Partizipialgruppe; halte das Subjekt gleich.",
    true,
  ),
  ...s(
    "Appositionen",
    [
      "Welcher Kasus für den Zusatz?",
      "Apposition → Kasusangleichung",
      "mit Paul, dem Lehrer",
    ],
    [
      ["Dativ", "Ich spreche mit Paul, [[dem Lehrer]].", "den Lehrer"],
      ["Akkusativ", "Ich sehe Paul, [[den Lehrer]].", "dem Lehrer"],
      ["Dativ", "Ich spreche mit Anna, [[der Ärztin]].", "die Ärztin"],
      ["Akkusativ", "Ich sehe Anna, [[die Ärztin]].", "der Ärztin"],
    ],
    "Ersetze Ich spreche mit durch Ich sehe.",
    "Beschreibe eine Person mit einer Apposition im passenden Kasus.",
  ),
  ...s(
    "Ausklammerung und Nachfeld",
    [
      "Vergleich im Nachfeld",
      "Vergleichsgruppe nach der Satzklammer",
      "gewartet als du",
    ],
    [
      [
        "Vergleich im Nachfeld",
        "Ich habe [[länger gewartet als du]].",
        "länger als du gewartet",
      ],
      [
        "Vergleich im Mittelfeld",
        "Ich habe [[länger als du gewartet]].",
        "länger gewartet als du",
      ],
      [
        "Vergleich im Nachfeld",
        "Ich habe [[mehr gelesen als du]].",
        "mehr als du gelesen",
      ],
      [
        "Vergleich im Mittelfeld",
        "Ich habe [[mehr als du gelesen]].",
        "mehr gelesen als du",
      ],
    ],
    "Stelle die Vergleichsgruppe ins Mittelfeld.",
    "Vergleiche zwei Tätigkeiten; stelle die Vergleichsgruppe ins Nachfeld.",
    true,
  ),
  ...s(
    ["Wissenschaftliches Hedging", "Feine Bedeutungsunterschiede im Modus"],
    ["Belegstärke kennzeichnen", "vorsichtige Möglichkeit", "könnte / zeigt"],
    [
      [
        "vorläufige Möglichkeit",
        "Das Ergebnis [[könnte einen Zusammenhang zeigen]].",
        "beweist einen Zusammenhang",
      ],
      [
        "beobachteter Zusammenhang",
        "Das Ergebnis [[zeigt einen Zusammenhang]].",
        "könnte einen Zusammenhang zeigen",
      ],
      [
        "vorläufige Möglichkeit",
        "Die Analyse [[könnte einen Unterschied zeigen]].",
        "beweist einen Unterschied",
      ],
      [
        "beobachteter Unterschied",
        "Die Analyse [[zeigt einen Unterschied]].",
        "könnte einen Unterschied zeigen",
      ],
    ],
    "Stelle einen beobachteten Zusammenhang fest; vermeide die Behauptung eines Kausalbeweises.",
    "Formuliere eine begründete, aber vorläufige Vermutung mit könnte.",
    true,
  ),
  ...s(
    ["Textkohäsion", "Kohärenz langer Beiträge", "Anapher und Katapher"],
    [
      "Worauf bezieht sich das Pronomen?",
      "eindeutige Rückverweisung",
      "Methode → sie / Verfahren → es",
    ],
    [
      ["die Methode", "Die Methode ist neu. [[Sie]] spart Zeit.", "Es"],
      ["das Verfahren", "Das Verfahren ist neu. [[Es]] spart Zeit.", "Sie"],
      ["die Lösung", "Die Lösung ist einfach. [[Sie]] funktioniert.", "Es"],
      ["das Modell", "Das Modell ist einfach. [[Es]] funktioniert.", "Sie"],
    ],
    "Ersetze die Methode durch das Verfahren.",
    "Beschreibe ein Vorgehen in zwei Sätzen und verwende einen eindeutigen Rückverweis.",
  ),
  ...s(
    [
      "Register und Stil",
      "Textsortenspezifische Grammatik",
      "Pragmatische Feinsteuerung",
      "Textsortentransformation",
    ],
    [
      "Bitte oder Anweisung?",
      "Adressat → Register",
      "Könnten Sie …? / Bitte …",
    ],
    [
      [
        "höfliche Bitte",
        "[[Könnten Sie mir bitte den Bericht senden?]]",
        "Senden Sie mir sofort den Bericht!",
      ],
      [
        "sachliche Arbeitsanweisung",
        "[[Bitte senden Sie mir den Bericht.]]",
        "Schick mir mal das Ding!",
      ],
      [
        "höfliche Bitte",
        "[[Könnten Sie bitte das Fenster schließen?]]",
        "Schließen Sie sofort das Fenster!",
      ],
      [
        "sachliche Arbeitsanweisung",
        "[[Bitte schließen Sie das Fenster.]]",
        "Mach das Ding zu!",
      ],
    ],
    "Formuliere eine sachliche Arbeitsanweisung mit Bitte senden Sie.",
    "Formuliere eine höfliche Bitte, die du beruflich verwenden könntest.",
    true,
  ),
  ...s(
    ["Parallelismus", "Rhetorische Syntax", "Syntaktischer Rhythmus"],
    [
      "Gleiche Satzmuster verbinden",
      "syntaktische Parallelität",
      "zu lesen und zu schreiben",
    ],
    [
      [
        "parallele Infinitive",
        "Ich versuche, [[zu lesen und zu schreiben]].",
        "zu lesen und ich schreibe",
      ],
      [
        "parallele Hauptsätze",
        "[[Ich lese und ich schreibe]].",
        "Ich lese und zu schreiben",
      ],
      [
        "parallele Infinitive",
        "Ich versuche, [[zu planen und zu prüfen]].",
        "zu planen und ich prüfe",
      ],
      [
        "parallele Hauptsätze",
        "[[Ich plane und ich prüfe]].",
        "Ich plane und zu prüfen",
      ],
    ],
    "Formuliere zwei parallele Hauptsätze statt einer Infinitivgruppe.",
    "Formuliere zwei eigene Ziele in einer parallelen Struktur.",
  ),
  ...s(
    "Komplexe Konditionalstrukturen",
    [
      "Bedingung ohne wenn",
      "Verb zuerst im Konditionalsatz",
      "Hätte ich Zeit, …",
    ],
    [
      [
        "wenn weglassen",
        "[[Hätte ich Zeit]], würde ich helfen.",
        "Ich hätte Zeit",
      ],
      [
        "mit wenn",
        "[[Wenn ich Zeit hätte]], würde ich helfen.",
        "Wenn hätte ich Zeit",
      ],
      [
        "wenn weglassen",
        "[[Wäre ich dort]], würde ich helfen.",
        "Ich wäre dort",
      ],
      [
        "mit wenn",
        "[[Wenn ich dort wäre]], würde ich helfen.",
        "Wenn wäre ich dort",
      ],
    ],
    "Füge wenn hinzu und stelle hätte ans Ende.",
    "Schreibe eine irreale Bedingung ohne wenn.",
  ),
  ...s(
    ["Interpunktion als Bedeutungssignal", "Syntax wissenschaftlicher Zitate"],
    [
      "Direktes Zitat einleiten",
      "vollständiger Einleitungssatz → Doppelpunkt",
      "Sie schreibt: „…“",
    ],
    [
      [
        "Einleitung eines ganzen Zitats",
        "Sie schreibt[[:]] „Der Versuch endet.“",
        ",",
      ],
      [
        "Zitat als Subjekt",
        "„Der Versuch endet.“[[]] ist der letzte Satz.",
        ":",
      ],
      [
        "Einleitung eines ganzen Zitats",
        "Er sagt[[:]] „Die Frage bleibt offen.“",
        ",",
      ],
      [
        "Zitat als Subjekt",
        "„Die Frage bleibt offen.“[[]] ist seine Aussage.",
        ":",
      ],
    ],
    "Verwende das Zitat als Subjekt: „Der Versuch endet.“ … ist der letzte Satz.",
    "Schreibe einen selbst erfundenen Satz als direktes Zitat mit Einleitung. Kennzeichne ihn als erfunden.",
  ),
  ...s(
    "Komplexe Einbettung",
    [
      "Frage im Nebensatz",
      "eingebettete Frage → Verbende",
      "ob er weiß, wann …",
    ],
    [
      [
        "Zeitfrage",
        "Ich frage, ob er weiß, [[wann sie kommt]].",
        "wann kommt sie",
      ],
      ["Ortsfrage", "Ich frage, ob er weiß, [[wo sie wohnt]].", "wo wohnt sie"],
      [
        "Zeitfrage",
        "Ich möchte wissen, ob sie weiß, [[wann er geht]].",
        "wann geht er",
      ],
      [
        "Ortsfrage",
        "Ich möchte wissen, ob sie weiß, [[wo er arbeitet]].",
        "wo arbeitet er",
      ],
    ],
    "Ersetze die Zeitfrage durch die Ortsfrage wo sie wohnt.",
    "Formuliere eine eigene Frage mit zwei klar geordneten Einbettungen.",
  ),
  ...s(
    "Ellipsen und Substitution",
    [
      "Wiederholtes Verb weglassen",
      "Koordination → rekonstruierbare Ellipse",
      "Anna liest …, Paul …",
    ],
    [
      [
        "ohne Verbwiederholung",
        "Anna liest Romane und Paul [[Zeitungen]].",
        "liest Zeitungen",
      ],
      [
        "mit Verbwiederholung",
        "Anna liest Romane und Paul [[liest Zeitungen]].",
        "Zeitungen",
      ],
      [
        "ohne Verbwiederholung",
        "Anna trinkt Tee und Paul [[Kaffee]].",
        "trinkt Kaffee",
      ],
      [
        "mit Verbwiederholung",
        "Anna trinkt Tee und Paul [[trinkt Kaffee]].",
        "Kaffee",
      ],
    ],
    "Ergänze das rekonstruierbare Verb im zweiten Teil.",
    "Formuliere zwei parallele Handlungen und spare das wiederholte Verb im zweiten Teil aus.",
    true,
  ),
  ...s(
    ["Ambiguitätskontrolle", "Fehlerdiagnose und präzise Reformulierung"],
    ["Wer ist gemeint?", "unklarer Bezug → Nomen wiederholen", "Anna / Maria"],
    [
      ["Anna ist müde", "Anna sagte Maria, dass [[Anna]] müde sei.", "sie"],
      ["Maria ist müde", "Anna sagte Maria, dass [[Maria]] müde sei.", "sie"],
      ["Paul ist krank", "Paul sagte Tim, dass [[Paul]] krank sei.", "er"],
      ["Tim ist krank", "Paul sagte Tim, dass [[Tim]] krank sei.", "er"],
    ],
    "Mache Maria statt Anna zur müden Person.",
    "Schreibe über zwei bekannte Personen und mache einen möglichen Pronomenbezug eindeutig.",
    true,
  ),
  ...s(
    ["Selbstreparatur im Sprechen", "Integrierte automatische Produktion"],
    [
      "Eine Angabe präzisieren",
      "Selbstreparatur → genauer gesagt",
      "am Morgen, genauer gesagt …",
    ],
    [
      [
        "Zeit präzisieren",
        "Ich komme morgens, [[genauer gesagt um neun]].",
        "genauer gesagt morgens",
      ],
      [
        "Ort präzisieren",
        "Ich warte draußen, [[genauer gesagt vor der Tür]].",
        "genauer gesagt draußen",
      ],
      [
        "Zeit präzisieren",
        "Wir treffen uns abends, [[genauer gesagt um acht]].",
        "genauer gesagt abends",
      ],
      [
        "Ort präzisieren",
        "Wir treffen uns im Park, [[genauer gesagt am Eingang]].",
        "genauer gesagt im Park",
      ],
    ],
    "Präzisiere den Ort statt der Zeit: Ich warte draußen, …",
    "Sage einen Plan laut und präzisiere eine Angabe mit genauer gesagt.",
    true,
  ),
  ...s(
    "Mehrsprachige Interferenzkontrolle",
    [
      "Eine Präposition übertragen?",
      "deutsche Rektion statt Wortübersetzung",
      "warten auf",
    ],
    [
      ["warten", "Ich warte [[auf]] dich.", "für"],
      ["sich interessieren", "Ich interessiere mich [[für]] Musik.", "auf"],
      ["warten", "Wir warten [[auf]] die Antwort.", "für"],
      ["sich interessieren", "Wir interessieren uns [[für]] Sprachen.", "auf"],
    ],
    "Verwende den Rahmen Ich interessiere mich … Musik.",
    "Schreibe einen deutschen Satz mit warten auf und vergleiche die Rektion mit einer anderen Sprache.",
  ),
  ...s(
    "Deixis und Perspektivsteuerung",
    ["Standort der sprechenden Person", "räumliche Deixis", "hier / dort"],
    [
      ["am eigenen Standort", "Das Büro ist [[hier]].", "dort"],
      ["an einem entfernten Standort", "Das Büro ist [[dort]].", "hier"],
      ["am eigenen Standort", "Der Eingang ist [[hier]].", "dort"],
      ["an einem entfernten Standort", "Der Eingang ist [[dort]].", "hier"],
    ],
    "Verlege den bezeichneten Ort weg vom eigenen Standort.",
    "Beschreibe zwei Orte relativ zu deinem aktuellen Standort.",
    true,
  ),
  ...s(
    "Skopus und Negation",
    ["Nicht alle oder keiner?", "Negationsskopus", "nicht alle / keiner"],
    [
      ["einige, aber nicht alle", "[[Nicht alle]] Gäste kamen.", "Keine"],
      ["kein einziger Gast", "[[Keine]] Gäste kamen.", "Nicht alle"],
      [
        "einige, aber nicht alle",
        "[[Nicht alle]] Fragen wurden beantwortet.",
        "Keine",
      ],
      [
        "keine einzige Frage",
        "[[Keine]] Fragen wurden beantwortet.",
        "Nicht alle",
      ],
    ],
    "Verneine jetzt das Kommen jedes einzelnen Gastes.",
    "Formuliere eine wahre Aussage mit nicht alle und erkläre ihren Skopus.",
    true,
  ),
  ...s(
    "Präsupposition und Implikatur",
    [
      "Welche Annahme wird vorausgesetzt?",
      "wieder → frühere Handlung",
      "wieder / erstmals",
    ],
    [
      [
        "hat schon früher hier gearbeitet",
        "Sie arbeitet [[wieder]] hier.",
        "erstmals",
      ],
      [
        "hat noch nie hier gearbeitet",
        "Sie arbeitet [[erstmals]] hier.",
        "wieder",
      ],
      [
        "hat schon früher dort gewohnt",
        "Er wohnt [[wieder]] dort.",
        "erstmals",
      ],
      ["hat noch nie dort gewohnt", "Er wohnt [[erstmals]] dort.", "wieder"],
    ],
    "Entferne die Annahme einer früheren Tätigkeit; verwende erstmals.",
    "Schreibe eine eigene Aussage mit wieder und benenne die vorausgesetzte frühere Handlung.",
    true,
  ),
  ...s(
    "Regionale Variation und Standardregister",
    ["Regional oder überregional?", "Komparativ → als", "größer als ich"],
    [
      [
        "überregionaler schriftlicher Standard",
        "Er ist größer [[als]] ich.",
        "wie",
      ],
      ["Gleichheit im Standard", "Er ist so groß [[wie]] ich.", "als"],
      [
        "überregionaler schriftlicher Standard",
        "Sie ist älter [[als]] ich.",
        "wie",
      ],
      ["Gleichheit im Standard", "Sie ist so alt [[wie]] ich.", "als"],
    ],
    "Drücke Gleichheit aus: Er ist so groß … ich.",
    "Vergleiche dich im schriftlichen Standard mit einer bekannten Person.",
    true,
  ),
];
