import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import {
  grammarUnits,
  speakingTopics,
  type GrammarUnit,
  type SpeakingTopic,
} from "../packages/content/src";

const outputPath = resolve(import.meta.dir, "../supabase/seed.sql");

function slugify(value: string): string {
  return value
    .replaceAll("ß", "ss")
    .normalize("NFD")
    .replaceAll(/[\u0300-\u036f]/g, "")
    .toLocaleLowerCase("de")
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/^-|-$/g, "");
}

function sqlText(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlNullableText(value: string | undefined): string {
  return value ? sqlText(value) : "null";
}

function assertUniqueSlugs(
  values: readonly string[],
  catalogName: string,
): void {
  const seen = new Set<string>();
  for (const value of values) {
    if (seen.has(value)) {
      throw new Error(`Duplicate ${catalogName} slug: ${value}`);
    }
    seen.add(value);
  }
}

function difficultyForLevel(level: string): number {
  return (
    {
      A1: 1,
      A2: 2,
      B1: 4,
      B2: 6,
      C1: 8,
      C2: 10,
    }[level] ?? 1
  );
}

function longRule(unit: GrammarUnit): string {
  const explanation = unit.explanation;
  return [
    explanation.overview,
    `Bildung:\n${explanation.formation.map((item) => `- ${item}`).join("\n")}`,
    `Verwendung:\n${explanation.usage.map((item) => `- ${item}`).join("\n")}`,
    `Wortstellung:\n${explanation.wordOrder.map((item) => `- ${item}`).join("\n")}`,
    `Besonderheiten:\n${explanation.specialCases.map((item) => `- ${item}`).join("\n")}`,
    `Merksatz: ${explanation.memoryTip}`,
  ].join("\n\n");
}

function grammarTopicStatement(unit: GrammarUnit): string {
  return `insert into public.grammar_topics (
  slug,
  title,
  level,
  category,
  short_rule,
  long_rule,
  common_error,
  recall_prompt,
  repair_prompt,
  transfer_prompt,
  difficulty_score,
  content_version,
  is_active
)
values (
  ${sqlText(slugify(unit.title))},
  ${sqlText(unit.title)},
  ${sqlText(unit.level)},
  'Grammatik',
  ${sqlText(unit.rule)},
  ${sqlText(longRule(unit))},
  ${sqlText(unit.commonError)},
  ${sqlText(unit.recallTest)},
  ${sqlText(unit.repairTest)},
  ${sqlText(unit.transferTest)},
  ${difficultyForLevel(unit.level)},
  1,
  true
)
on conflict (slug) do update set
  title = excluded.title,
  level = excluded.level,
  category = excluded.category,
  short_rule = excluded.short_rule,
  long_rule = excluded.long_rule,
  common_error = excluded.common_error,
  recall_prompt = excluded.recall_prompt,
  repair_prompt = excluded.repair_prompt,
  transfer_prompt = excluded.transfer_prompt,
  difficulty_score = excluded.difficulty_score,
  content_version = excluded.content_version,
  is_active = excluded.is_active;`;
}

function exampleStatement(
  unit: GrammarUnit,
  exampleText: string,
  exampleType: "core" | "error" | "transfer",
  sortOrder: number,
): string {
  return `insert into public.topic_examples (
  grammar_topic_id,
  example_text,
  translation_text,
  example_type,
  sort_order
)
select
  gt.id,
  ${sqlText(exampleText)},
  null,
  ${sqlText(exampleType)},
  ${sortOrder}
from public.grammar_topics gt
where gt.slug = ${sqlText(slugify(unit.title))}
on conflict (grammar_topic_id, example_text, example_type) do update set
  sort_order = excluded.sort_order;`;
}

function speakingTopicStatement(topic: SpeakingTopic): string {
  const followups = [
    "Warum denkst du das?",
    "Gib ein konkretes Beispiel.",
    "Übertrage die Antwort auf eine andere Zeit oder Person.",
  ];

  return `insert into public.speaking_topics (
  slug,
  title,
  level,
  domain,
  prompt_text,
  followup_prompts,
  model_answer,
  target_grammar,
  content_version,
  is_active
)
values (
  ${sqlText(slugify(topic.topic))},
  ${sqlText(topic.topic)},
  ${sqlText(topic.level)},
  ${sqlText(topic.category)},
  ${sqlText(topic.task)},
  ${sqlText(JSON.stringify(followups))}::jsonb,
  ${sqlNullableText(topic.modelAnswer)},
  ${sqlNullableText(topic.targetGrammar)},
  1,
  true
)
on conflict (slug) do update set
  title = excluded.title,
  level = excluded.level,
  domain = excluded.domain,
  prompt_text = excluded.prompt_text,
  followup_prompts = excluded.followup_prompts,
  model_answer = excluded.model_answer,
  target_grammar = excluded.target_grammar,
  content_version = excluded.content_version,
  is_active = excluded.is_active;`;
}

const grammarSlugs = grammarUnits.map((unit) => slugify(unit.title));
const speakingSlugs = speakingTopics.map((topic) => slugify(topic.topic));
assertUniqueSlugs(grammarSlugs, "grammar");
assertUniqueSlugs(speakingSlugs, "speaking");

const statements: string[] = [
  "-- Generated by `bun run db:seed:generate`. Do not hand-edit.",
  "-- Seeds 144 CEFR-aligned grammar units and 79 integrated conversation topics.",
  "begin;",
];

for (const unit of grammarUnits) {
  statements.push(grammarTopicStatement(unit));
  unit.examples.forEach((example, index) => {
    statements.push(exampleStatement(unit, example, "core", index));
  });
  statements.push(
    exampleStatement(unit, unit.commonError, "error", 100),
    exampleStatement(unit, unit.transferTest, "transfer", 200),
  );
}

for (const topic of speakingTopics) {
  statements.push(speakingTopicStatement(topic));
}

statements.push("commit;", "");

await mkdir(dirname(outputPath), { recursive: true });
await Bun.write(outputPath, statements.join("\n\n"));

console.log(
  `Generated ${outputPath} with ${grammarUnits.length} grammar units and ${speakingTopics.length} speaking topics.`,
);
