/** Original project-authored practice drafts. No independent human review is claimed. */
export interface PromptDraft {
  prompt: string;
  answers: string[];
}
export interface SupplementaryDraft {
  id: string;
  placement: string;
  example: string;
  retrieve: PromptDraft;
  vary: PromptDraft;
  repair: PromptDraft;
  produce: string;
  transfer: string;
  retain: string;
}
const closed = (prompt: string, ...answers: string[]): PromptDraft => ({prompt, answers});
export const supplementaryGrammar: SupplementaryDraft[] = [
  {
    id: "en.c.113", placement: "A2", example: "If I miss the bus, I walk to work.",
    retrieve: closed("State a regular routine, using if: I miss the bus. As a regular consequence, I walk to work.", "If I miss the bus, I walk to work.", "I walk to work if I miss the bus."),
    vary: closed("Keep the routine meaning. Replace I with she: If I miss the bus, I walk to work.", "If she misses the bus, she walks to work.", "She walks to work if she misses the bus."),
    repair: closed("Correct only the agreement: If the printer stop, we restart it.", "If the printer stops, we restart it."),
    produce: "Describe two recurring situations in your day and what normally happens in each. Make clear that these are routines.",
    transfer: "Explain a simple workplace rule to a new colleague: describe the condition and its usual consequence. Choose your own situation.",
    retain: "Without reopening the rule, describe a recurring travel problem and your usual response. Then explain how a one-time future prediction would differ.",
  },
  {
    id: "en.c.114", placement: "A1", example: "These folders beside me are ready; those folders near the door are not.",
    retrieve: closed("Choose this/that/these/those. The two folders are beside the speaker: ___ folders are ready. Write the full sentence.", "These folders are ready."),
    vary: closed("The folder is now far from the speaker. Change only the demonstrative: This folder is ready.", "That folder is ready."),
    repair: closed("Correct the demonstrative number: This shoes are wet.", "These shoes are wet."),
    produce: "Describe two nearby objects and one object farther away. Give enough context for the listener to identify them.",
    transfer: "On a video call, distinguish the document currently on screen from an earlier proposal. Make each reference clear.",
    retain: "Imagine a shop counter. Refer to one item near you and several items on a distant shelf without naming them twice.",
  },
  {
    id: "en.c.115", placement: "A2", example: "Someone has left a message, but nobody knows who called.",
    retrieve: closed("Use someone/somebody for an unidentified person: ___ has left a message. Write the full sentence.", "Someone has left a message.", "Somebody has left a message."),
    vary: closed("Express complete absence of people while keeping present tense: Someone is waiting outside.", "Nobody is waiting outside.", "No one is waiting outside."),
    repair: closed("Correct agreement only: Everybody know the answer.", "Everybody knows the answer."),
    produce: "Describe a lost object: what someone noticed, what nobody knows, and what you still need to find out.",
    transfer: "Write a short message asking whether any person can help with an unfamiliar software problem. Do not assume a helper already exists.",
    retain: "Explain the difference between an unidentified person arriving and no person arriving, using complete sentences.",
  },
  {
    id: "en.c.116", placement: "A2", example: "Maya and Leo help each other with their applications.",
    retrieve: closed("Maya helps Leo, and Leo helps Maya. Combine with a reciprocal pronoun: Maya and Leo help ...", "Maya and Leo help each other.", "Maya and Leo help one another."),
    vary: closed("Keep the mutual relation and change help to trust: The neighbours help each other.", "The neighbours trust each other.", "The neighbours trust one another."),
    repair: closed("The intended meaning is mutual help, not self-help. Correct the pronoun: We help ourselves.", "We help each other.", "We help one another."),
    produce: "Describe two ways you and another person support one another. Distinguish mutual actions from things you each do alone.",
    transfer: "Explain how two teams exchange feedback. Keep clear who gives feedback to whom.",
    retain: "Describe a mutual promise and contrast it with a promise each person makes to themselves.",
  },
  {
    id: "en.c.117", placement: "A1", example: "My charger is black. The white one is yours.",
    retrieve: closed("Replace my bag with an independent possessive pronoun: This is my bag. Begin: This bag is ...", "This bag is mine."),
    vary: closed("The bag belongs to us, not to me. Change only the possessive pronoun: This bag is mine.", "This bag is ours."),
    repair: closed("Correct the possessive form without adding a noun: The blue notebook is her.", "The blue notebook is hers."),
    produce: "Compare an object that belongs to you with one belonging to a friend. Avoid repeating the object name in every sentence.",
    transfer: "Two people have mixed up identical umbrellas. Explain which is yours and which belongs to the other person.",
    retain: "Explain a shared ownership situation using ours, then contrast it with ownership by another group.",
  },
  {
    id: "en.c.118", placement: "B1", example: "The list of missing documents is on the desk.",
    retrieve: closed("Choose is/are from the subject head: The box of spare cables ___ heavy. Write the full sentence.", "The box of spare cables is heavy."),
    vary: closed("Change the head noun to plural and preserve agreement: The box of spare cables is heavy.", "The boxes of spare cables are heavy."),
    repair: closed("Correct agreement only: The quality of these photographs are excellent.", "The quality of these photographs is excellent."),
    produce: "Describe a collection of objects and then describe the individual objects. Use one singular head and one plural head.",
    transfer: "Explain the condition of equipment in an inventory report. Include a long subject with an of-phrase, and make its agreement clear.",
    retain: "Write a sentence whose singular subject contains a plural noun inside a prepositional phrase. Identify the agreement controller afterward.",
  },
  {
    id: "en.c.119", placement: "A2", example: "Who called Anna? Who did Anna call?",
    retrieve: closed("Anna called an unknown person. Ask for that person, keeping Anna as the caller. Use who.", "Who did Anna call?"),
    vary: closed("An unknown person called Anna. Ask for the caller, using who.", "Who called Anna?"),
    repair: closed("Ask about the person you met. Correct ordinary past-simple question structure: Who you met yesterday?", "Who did you meet yesterday?"),
    produce: "Ask two questions about a meeting: one about the person who organised it and one about the person the organiser invited.",
    transfer: "A colleague reports a delivery but leaves out the sender and receiver. Ask separate questions that distinguish those roles.",
    retain: "Invent a short event involving two people. Ask first about its unknown actor and then about its unknown object.",
  },
  {
    id: "en.c.120", placement: "B1", example: "It is useful to check the address before leaving.",
    retrieve: closed("Use introductory it, preserving the evaluation: To check the address is useful.", "It is useful to check the address."),
    vary: closed("Put the infinitive clause first: It is important to save your work.", "To save your work is important."),
    repair: closed("Supply the missing weather subject: Is raining outside.", "It is raining outside."),
    produce: "Give a practical recommendation using introductory it and a following infinitive or that-clause.",
    transfer: "Explain why a change in your work process matters. Choose whether to place the activity first or introduce it with it.",
    retain: "Write one weather sentence and one evaluation with a postponed clause. Explain why it does not refer to an ordinary object in either.",
  },
  {
    id: "en.c.121", placement: "B1", example: "She bought a small wooden desk.",
    retrieve: closed("Use neutral adjective order, with size before material: a / wooden / small / desk. Write the noun phrase.", "a small wooden desk"),
    vary: closed("Keep size before material and replace wooden with metal: a small wooden desk.", "a small metal desk"),
    repair: closed("Use the neutral size-before-material order: a wooden small chair.", "a small wooden chair"),
    produce: "Describe an everyday object using two compatible adjectives. Explain any unusual emphasis if you choose a marked order.",
    transfer: "Write a clear second-hand sale description distinguishing two similar objects by size, age or material.",
    retain: "Describe an object without consulting a model. Then separate a factual material modifier from an opinion about the object.",
  },
  {
    id: "en.c.122", placement: "B1", example: "This is a friend of mine, not my only friend.",
    retrieve: closed("Use a double genitive to mean one of my friends: She is a friend ___ . Write the full sentence.", "She is a friend of mine."),
    vary: closed("The friend is one of her friends. Change only the possessive pronoun: She is a friend of mine.", "She is a friend of hers."),
    repair: closed("Correct only the independent possessive form: He is a colleague of my.", "He is a colleague of mine."),
    produce: "Introduce one of your acquaintances without implying they are your only acquaintance. Then describe an object's relationship to another object.",
    transfer: "Explain who owns a document and distinguish ownership from authorship. Choose a genitive or an of-phrase suitable for each relation.",
    retain: "Compare a friend of mine with my only friend in two short situations. Preserve the difference in reference.",
  },
  {
    id: "en.c.123", placement: "C1", example: "They recommend that the door remain closed.",
    retrieve: closed("Complete this formal recommendation with be or should be: We recommend that the file ___ encrypted. Write the full sentence.", "We recommend that the file be encrypted.", "We recommend that the file should be encrypted."),
    vary: closed("Replace the base-form mandative with a should-clause: They insist that the room be quiet.", "They insist that the room should be quiet."),
    repair: closed("Express a formal recommendation, not a factual claim. Correct: I recommend that he is present. Use the mandative base form or should.", "I recommend that he be present.", "I recommend that he should be present."),
    produce: "Write a formal recommendation about a practical procedure. Separate what you recommend from what currently happens.",
    transfer: "Respond to a committee discussing a new rule. State a required or desired action without presenting it as an existing fact.",
    retain: "Express a requirement in a that-clause and paraphrase it with should. Keep its desired meaning and identify the person who must act.",
  },
  {
    id: "en.c.124", placement: "A2", example: "She studies every day and is studying now.",
    retrieve: closed("Write only the third-person singular present form of study.", "studies"),
    vary: closed("Write only the -ing form of make.", "making"),
    repair: closed("Correct only the suffix spelling: He is runing home.", "He is running home."),
    produce: "Write sentences containing studies, making and stopped. Keep the spelling change appropriate to each suffix.",
    transfer: "Edit a short note about a hobby. Include a consonant-plus-y verb, a final-e verb and a doubled-consonant form; check each spelling in context.",
    retain: "Write the past form of plan and the third-person singular form of try in original sentences. Explain the two spelling changes afterward.",
  },
  {
    id: "de.c.145", placement: "B2", example: "Bis Freitag werde ich den Bericht fertiggestellt haben.",
    retrieve: closed("Bilde Futur II mit ich: den Bericht bis Freitag fertigstellen. Beginne mit Bis Freitag.", "Bis Freitag werde ich den Bericht fertiggestellt haben."),
    vary: closed("Ersetze ich durch wir: Bis Freitag werde ich den Bericht fertiggestellt haben.", "Bis Freitag werden wir den Bericht fertiggestellt haben."),
    repair: closed("Korrigiere nur das Hilfsverb im Infinitiv: Bis morgen wird sie angekommen haben.", "Bis morgen wird sie angekommen sein."),
    produce: "Beschreibe einen Abschluss vor einem künftigen Zeitpunkt. Formuliere danach getrennt eine Vermutung über etwas Vergangenes.",
    transfer: "Ein Paket ist nicht mehr im Flur. Äußere eine vorsichtige Vermutung über seinen Verbleib und kennzeichne deine Unsicherheit.",
    retain: "Nenne eine Tätigkeit, die vor einem gewählten Termin abgeschlossen sein wird. Erkläre, ob dein Satz Zukunft oder Vermutung über Vergangenes ausdrückt.",
  },
  {
    id: "de.c.146", placement: "C1", example: "Sie hat länger arbeiten müssen.",
    retrieve: closed("Setze ins Perfekt: Sie muss länger arbeiten.", "Sie hat länger arbeiten müssen."),
    vary: closed("Verbinde mit weil und nutze die standardsprachliche Oberfeldstellung: Sie hat länger arbeiten müssen.", "weil sie länger hat arbeiten müssen"),
    repair: closed("Korrigiere das Verbgefüge: Er hat heute arbeiten gemusst.", "Er hat heute arbeiten müssen."),
    produce: "Berichte mit einem Modalverb im Perfekt, was du gestern tun musstest oder konntest. Prüfe den gesamten Verbkomplex.",
    transfer: "Erkläre eine Verspätung mit einem weil-Satz und einem Modalverb im Perfekt. Die Erklärung soll zu einer konkreten Situation passen.",
    retain: "Formuliere dieselbe Verpflichtung zuerst im Hauptsatzperfekt und dann als Begründung mit weil. Erhalte Person und Zeitbezug.",
  },
  {
    id: "de.c.147", placement: "B1", example: "Sie ist stolz auf ihre Arbeit und ihrem Bruder ähnlich.",
    retrieve: closed("Ergänze die passende Präposition: Sie ist stolz ___ ihre Arbeit. Schreibe den ganzen Satz.", "Sie ist stolz auf ihre Arbeit."),
    vary: closed("Ersetze dem Vater durch die Mutter und erhalte den Dativ: Er ist dem Vater ähnlich.", "Er ist der Mutter ähnlich."),
    repair: closed("Korrigiere nur die vom Adjektiv verlangte Präposition: Ich bin stolz über meinen Fortschritt.", "Ich bin stolz auf meinen Fortschritt."),
    produce: "Beschreibe einen Zustand mit stolz auf, zufrieden mit oder ähnlich plus Dativ. Verwende einen passenden vollständigen Bezug.",
    transfer: "Gib einer Kollegin wertschätzendes Feedback. Beschreibe, womit du zufrieden bist, und erkläre einen konkreten Grund.",
    retain: "Formuliere zwei Sätze mit unterschiedlich angeschlossenen Adjektiven. Markiere erst danach Präposition und Kasus.",
  },
  {
    id: "de.c.148", placement: "A2", example: "Ich nehme diesen Ordner, nicht jenen.",
    retrieve: closed("Ergänze dieser im Akkusativ maskulin: Ich nehme ___ Ordner. Schreibe den ganzen Satz.", "Ich nehme diesen Ordner."),
    vary: closed("Setze der Ordner in den Plural: Ich nehme diesen Ordner.", "Ich nehme diese Ordner."),
    repair: closed("Korrigiere nur die Demonstrativendung: Mit diesen Buch arbeite ich.", "Mit diesem Buch arbeite ich."),
    produce: "Unterscheide zwei Gegenstände mit demonstrativen Formen. Sage klar, welchen du meinst und was du damit machst.",
    transfer: "Du besprichst zwei frühere Vorschläge. Verweise eindeutig auf einen davon und formuliere eine konkrete Entscheidung.",
    retain: "Beschreibe die Auswahl eines Gegenstands und die Arbeit mit diesem Gegenstand. Achte auf den Kasuswechsel.",
  },
  {
    id: "de.c.149", placement: "A1", example: "Das Mädchen trägt einen Rucksack. Der Rucksack ist schwer.",
    retrieve: closed("Ergänze den bestimmten Artikel im Nominativ: ___ Mädchen wartet. Schreibe den ganzen Satz.", "Das Mädchen wartet."),
    vary: closed("Setze das Mädchen in den Plural: Das Mädchen wartet.", "Die Mädchen warten."),
    repair: closed("Korrigiere Artikel und Adjektivendung: Der kleine Mädchen liest.", "Das kleine Mädchen liest."),
    produce: "Stelle drei Nomen aus deinem Alltag mit Artikel vor und verwende sie in Sätzen. Prüfe das Genus anhand eines Wörterbuchs erst nach deinem Versuch.",
    transfer: "Beschreibe unbekannte Gegenstände in einem Arbeitsraum. Halte Artikel und spätere Bezüge konsistent; kennzeichne unsicheres Genus.",
    retain: "Verwende Mädchen, Zeitung und Tisch in eigenen Nominalgruppen. Begründe anschließend, welches Genus lexikalisch gelernt werden muss.",
  },
  {
    id: "de.c.150", placement: "B2", example: "Das ist die Kollegin, deren Fahrrad vor dem Haus steht.",
    retrieve: closed("Verbinde mit einem Relativsatz: Das ist die Kollegin. Ihr Fahrrad steht draußen.", "Das ist die Kollegin, deren Fahrrad draußen steht."),
    vary: closed("Ersetze die Kollegin durch der Kollege: Das ist die Kollegin, deren Fahrrad draußen steht.", "Das ist der Kollege, dessen Fahrrad draußen steht."),
    repair: closed("Korrigiere nur das genitivische Relativattribut: Das ist der Mann, deren Hund schläft.", "Das ist der Mann, dessen Hund schläft."),
    produce: "Beschreibe eine Person über einen Gegenstand, der ihr gehört. Verwende dessen oder deren mit eindeutigem Antezedens.",
    transfer: "In einer Gruppe gehen mehrere Taschen verloren. Identifiziere eine Person durch ein Merkmal ihrer Tasche, ohne den Besitzbezug zu vertauschen.",
    retain: "Bilde einen Relativsatz über eine Frau und einen über mehrere Personen. Begründe deine Wahl zwischen dessen und deren.",
  },
  {
    id: "de.c.151", placement: "A2", example: "Der Zug ist schneller als der Bus, aber genauso teuer wie das Taxi.",
    retrieve: closed("Ergänze als oder wie: Der Zug ist schneller ___ der Bus. Schreibe den ganzen Satz.", "Der Zug ist schneller als der Bus."),
    vary: closed("Drücke Gleichheit aus: Der Zug ist schnell. Der Bus ist genauso schnell. Beginne mit Der Zug.", "Der Zug ist so schnell wie der Bus.", "Der Zug ist genauso schnell wie der Bus."),
    repair: closed("Korrigiere den neutralen standardsprachlichen Vergleich: Der Bus ist langsamer wie der Zug.", "Der Bus ist langsamer als der Zug."),
    produce: "Vergleiche zwei Verkehrsmittel hinsichtlich eines Unterschieds und einer Gemeinsamkeit. Erhalte die Vergleichsrichtung.",
    transfer: "Hilf jemandem bei der Wahl zwischen zwei Angeboten. Beschreibe mindestens einen Gleichheits- und einen Ungleichheitsvergleich.",
    retain: "Vergleiche zwei vertraute Tätigkeiten mit als und so ... wie, ohne die Beispiele erneut zu lesen.",
  },
  {
    id: "de.c.152", placement: "B1", example: "Es ist wichtig, regelmäßig Pausen zu machen.",
    retrieve: closed("Formuliere mit vorangestelltem es: Regelmäßig Pausen zu machen ist wichtig.", "Es ist wichtig, regelmäßig Pausen zu machen."),
    vary: closed("Stelle die Infinitivgruppe voran: Es ist sinnvoll, die Adresse zu prüfen.", "Die Adresse zu prüfen ist sinnvoll."),
    repair: closed("Ergänze nur das unpersönliche Subjekt: Regnet heute.", "Es regnet heute."),
    produce: "Formuliere eine Bewertung mit nachgestelltem Inhalt und einen Wettersatz. Beschreibe die unterschiedliche Funktion von es.",
    transfer: "Erkläre eine nützliche Änderung im Alltag. Wähle eine natürliche Informationsreihenfolge und behalte den Satz vollständig.",
    retain: "Drücke dieselbe Bewertung einmal mit Korrelat-es und einmal mit vorangestellter Infinitivgruppe aus.",
  },
  {
    id: "de.c.153", placement: "B1", example: "Die Haustür ist eine Tür des Hauses; der Hausschlüssel ist ein Schlüssel für das Haus.",
    retrieve: closed("Bilde ein geläufiges Kompositum aus Haus und Tür und ergänze den bestimmten Artikel im Nominativ.", "die Haustür"),
    vary: closed("Bilde ein geläufiges Kompositum aus Haus und Schlüssel und ergänze den bestimmten Artikel im Nominativ.", "der Hausschlüssel"),
    repair: closed("Korrigiere nur den Artikel nach dem nominalen Kopf: das Haustür.", "die Haustür"),
    produce: "Erkläre zwei gebräuchliche Komposita aus deinem Alltag. Identifiziere den Kopf und beschreibe die Beziehung der Bestandteile.",
    transfer: "Erkläre einem neuen Teammitglied einen zusammengesetzten Fachbegriff. Prüfe, ob die gemeinte Beziehung für Außenstehende verständlich ist.",
    retain: "Bilde keine Fantasiewörter: Nenne zwei bekannte Komposita und kontrolliere danach Genus und eventuelles Fugenelement.",
  },
  {
    id: "de.c.154", placement: "B1", example: "Die beiden Nachbarn helfen einander.",
    retrieve: closed("Anna hilft Ben, und Ben hilft Anna. Fasse mit einander zusammen: Anna und Ben ...", "Anna und Ben helfen einander."),
    vary: closed("Verdeutliche dieselbe wechselseitige Beziehung mit sich gegenseitig: Anna und Ben helfen einander.", "Anna und Ben helfen sich gegenseitig."),
    repair: closed("Gemeint ist gegenseitige Hilfe, keine Selbsthilfe. Formuliere eindeutig: Die Nachbarn helfen sich selbst.", "Die Nachbarn helfen einander.", "Die Nachbarn helfen sich gegenseitig."),
    produce: "Beschreibe eine gegenseitige Handlung zweier Personen. Vermeide eine unbeabsichtigte rein reflexive Lesart.",
    transfer: "Zwei Arbeitsgruppen tauschen Informationen aus. Erkläre die Beziehung und verwende bei Bedarf miteinander oder einander.",
    retain: "Formuliere einen eindeutig reziproken und einen eindeutig reflexiven Satz. Erkläre, wer jeweils handelt und betroffen ist.",
  },
  {
    id: "de.c.155", placement: "B1", example: "Niemand ist gekommen. Nicht alle haben abgesagt.",
    retrieve: closed("Keine Person ist gekommen. Ersetze keine Person durch niemand.", "Niemand ist gekommen."),
    vary: closed("Formuliere mit keine Person: Niemand wartet draußen.", "Keine Person wartet draußen."),
    repair: closed("Korrigiere nur die Kongruenz: Niemand sind gekommen.", "Niemand ist gekommen."),
    produce: "Beschreibe eine Situation mit keiner Person und eine mit nur einem Teil der Personen. Halte keiner und nicht alle auseinander.",
    transfer: "Berichte über Rückmeldungen auf eine Einladung. Unterscheide sorgfältig zwischen niemand hat geantwortet und nicht alle haben geantwortet.",
    retain: "Formuliere eine verneinte Personenreferenz und eine verneinte Sachreferenz. Achte auf Kongruenz und Negationsreichweite.",
  },
  {
    id: "de.c.156", placement: "B2", example: "Sie versucht, regelmäßig spazieren zu gehen.",
    retrieve: closed("Schreibe die Infinitivgruppe korrekt mit Leerzeichen: spazieren + zu + gehen.", "spazieren zu gehen"),
    vary: closed("Schreibe nur den einfachen Infinitiv ohne zu: spazieren zu gehen.", "spazieren gehen"),
    repair: closed("Korrigiere nur die Wortgrenze: Wir wollen heute spazierengehen.", "Wir wollen heute spazieren gehen."),
    produce: "Schreibe zwei eigene Sätze mit spazieren gehen, einen davon mit einer zu-Infinitivgruppe. Prüfe die Wortgrenzen.",
    transfer: "Überarbeite eine kurze Freizeitnachricht auf Getrennt- und Zusammenschreibung. Unbekannte lexikalische Fälle bleiben bis zur Wörterbuchprüfung offen.",
    retain: "Schreibe einen Plan mit spazieren gehen und eine Absicht mit spazieren zu gehen, ohne das Modell erneut zu öffnen.",
  },
];
