import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { isRecord } from "../shared/learning-core/src/automaticity/contracts";
import { parseBenchmarkInput, qualifyCandidate } from "../shared/learning-core/src/automaticity/qualification";
import { transformerConfigurationSha256, type TransformerConfig } from "../shared/learning-core/src/automaticity/transformer";
import { validateTransformerRelease, type TransformerRelease } from "../shared/learning-core/src/automaticity/transformer-route";
import { digest, evidenceFile, validateEvaluationEvidence, type BenchmarkDraft, type PredictionRun } from "./lib/model-benchmark";
const root=resolve(import.meta.dir,".."),[inputPath,reviewPath,outputPath]=Bun.argv.slice(2);
if(!inputPath||!reviewPath||!outputPath)throw Error("Usage: bun scripts/compile-transformer-release.ts qualification-input.json independent-release-review.json NEW-release.json");
const inputText=await readFile(resolve(root,inputPath),"utf8"),input=parseBenchmarkInput(JSON.parse(inputText));
await validateEvaluationEvidence(root,input);
const qualification=qualifyCandidate(input.cases,input.predictions,input.candidate);
if(!qualification.eligibleForReleaseReview)throw Error(`Candidate cannot be released: ${qualification.reasons.join('; ')}`);
const config=JSON.parse(await readFile(resolve(root,"docs/model-evaluation/transformer-candidate.json"),"utf8")) as TransformerConfig;
const configurationSha256=await transformerConfigurationSha256(config);
if(config.candidateId!==input.candidate.id||config.version!==input.candidate.version)throw Error("Different model/configuration than the evaluated candidate");
const value=JSON.parse(inputText) as {evaluationEvidence:{run:{path:string;sha256:string}}};
const run=JSON.parse(await evidenceFile(root,value.evaluationEvidence.run)) as PredictionRun;
if(run.configuration?.providerConfigurationSha256!==configurationSha256)throw Error("Final benchmark did not pin this provider configuration");
const reviewText=await readFile(resolve(root,reviewPath),"utf8"),review:unknown=JSON.parse(reviewText);
if(!isRecord(review)||review.schemaVersion!==1||review.decision!=="approved"||typeof review.reviewerId!=="string"||!review.reviewerId.trim()||/codex|chatgpt|synthetic|fixture/i.test(review.reviewerId)||typeof review.role!=="string"||!review.role.trim()||typeof review.note!=="string"||review.note.trim().length<20||review.qualificationSha256!==digest(inputText)||review.configurationSha256!==configurationSha256||typeof review.reviewedAt!=="string"||!Number.isFinite(Date.parse(review.reviewedAt))||Date.parse(review.reviewedAt)>Date.now()||Date.parse(review.reviewedAt)<Date.parse(run.finishedAt)||input.cases.some(row=>(row as BenchmarkDraft).authoredBy===review.reviewerId))throw Error("An actual independent, dated release review bound to these results is required");
const rows=input.cases.filter(row=>row.partition==="final") as BenchmarkDraft[];
const approvals=["en","de"].flatMap(language=>{
 const selected=rows.filter(row=>row.language===language);if(!selected.length)return [];
 if(selected.some(row=>row.modality!=="writing"))throw Error("This text adapter cannot approve spoken assessment");
 const scopes=[...new Map(selected.map(row=>{const scope={constructionId:row.constructionId,taskVersion:row.taskVersion,rubricVersion:row.rubricVersion,modality:row.modality};return [JSON.stringify(scope),scope];})).values()];
 return [{approved:true,evaluatorId:config.candidateId,evaluatorVersion:config.version,language:language as "en"|"de",constructionIds:[...new Set(scopes.map(row=>row.constructionId))],rubricVersions:[...new Set(scopes.map(row=>row.rubricVersion))],modalities:["writing" as const],scopes,benchmarkSha256:digest(inputText),configurationSha256}];
});
const release:TransformerRelease={schemaVersion:1,kind:"qualified-local-transformer-release",config,configurationSha256,approvals,review:{reviewerId:review.reviewerId,reviewedAt:review.reviewedAt,evidenceSha256:digest(reviewText),qualificationSha256:digest(inputText)}};
await validateTransformerRelease(release);
const output=resolve(root,outputPath);await mkdir(dirname(output),{recursive:true});const text=JSON.stringify(release,null,2)+'\n';await writeFile(output,text,{flag:"wx"});
console.log(JSON.stringify({output,sha256:digest(text),scopes:approvals.reduce((sum,row)=>sum+row.scopes.length,0),activated:false,instruction:"After deployment approval, set AUTOMATICITY_TRANSFORMER_RELEASE and AUTOMATICITY_TRANSFORMER_RELEASE_SHA256 on the server. This command does not change settings."}));
