import {readFileSync,writeFileSync} from "node:fs";
const apps=[{lang:"en",root:"Apps/English/English-Automaticity/apps/web",feature:"features",staticNames:["daily","grammar"]},{lang:"de",root:"Apps/Deutsch-Automaticity/apps/web",feature:"src/features",staticNames:["heute","grammatik"]}] as const;
for(const app of apps){
  const en=app.lang==="en";
  for(const name of app.staticNames){const path=`${app.root}/public/replacements/${app.lang}/${name}.html`;let text=readFileSync(path,"utf8");
    const banner=`<aside aria-label="${en?"Independent practice":"Eigenständiges Üben"}" style="background:#eef4ff;border-bottom:1px solid #bfcee8;padding:14px 24px;display:flex;align-items:center;justify-content:center;gap:18px;flex-wrap:wrap;color:#173d7a;font:500 15px/1.5 system-ui"><span>${en?"Build recall with your own answers, saved drafts, and recordings.":"Übe den Abruf mit eigenen Antworten, gespeicherten Entwürfen und Aufnahmen."}</span><a href="/practice" style="background:#2258c0;border-radius:9px;padding:10px 16px;color:white;text-decoration:none">${en?"Start independent practice":"Eigenständig üben"}</a></aside>`;
    text=text.replace(/(<body[^>]*>)/,`$1\n${banner}`);writeFileSync(path,text);
  }
  const sw=`${app.root}/public/sw.js`;let source=readFileSync(sw,"utf8");source=source.replace(/const CACHE = "[^"]+";/,`const CACHE = "${en?"english-automaticity":"deutschflow"}-automaticity-v2-20260905";`);
  source=source.replace(en?"const PRECACHE = [":"const CORE = [",`${en?"const PRECACHE":"const CORE"} = [\n  "/practice",\n  "/learning-core/practice.js",\n  "/learning-core/practice.css",\n  "/learning-core/curriculum-${app.lang}.json",`);writeFileSync(sw,source);
  const path=`${app.root}/${app.feature}/${en?"components":"progress"}/automaticity-evidence-summary.tsx`;
  writeFileSync(path,`"use client";
import {useEffect,useState} from "react";
import {readAutomaticityEvents,reduceAutomaticityEvents,type ConstructionProgress} from "@automaticity/learning-core/automaticity";
export function AutomaticityEvidenceSummary(){
  const [rows,setRows]=useState<ConstructionProgress[]|null>(null);
  const [problem,setProblem]=useState("");
  useEffect(()=>{const refresh=()=>{try{const read=readAutomaticityEvents(localStorage,"${app.lang}");const reduced=reduceAutomaticityEvents(read.events,"${app.lang}",new Date().toISOString());setRows(reduced.progress);if(read.unreadable.length||reduced.rejected.length)setProblem(${JSON.stringify(en?"Some records could not be verified. They remain in your complete backup.":"Einige Einträge konnten nicht geprüft werden. Sie bleiben in deiner vollständigen Sicherung erhalten.")});}catch{setProblem(${JSON.stringify(en?"Saved evidence is unavailable.":"Gespeicherte Nachweise sind nicht verfügbar.")});}};refresh();window.addEventListener("storage",refresh);return()=>window.removeEventListener("storage",refresh);},[]);
  return <section className="rounded-2xl border border-blue-200 bg-white p-5" aria-label="${en?"Independent learning evidence":"Unabhängige Lernnachweise"}"><h2 className="text-xl font-bold">${en?"Evidence from your own responses":"Nachweise aus deinen eigenen Antworten"}</h2><p className="my-3 text-sm">${en?"Hints, model answers and repeated repairs remain practice. Unknown skills need a suitable review before they receive an accuracy score.":"Hinweise, Musterlösungen und wiederholte Korrekturen bleiben Übungen. Unbekannte Fähigkeiten benötigen eine passende Prüfung, bevor sie einen Genauigkeitswert erhalten."}</p><div className="grid gap-4 sm:grid-cols-2">{(["writing","speaking"] as const).map(mode=>{const samples=(rows??[]).filter(row=>row.modality===mode);const checked=samples.reduce((n,row)=>n+row.independentAssessed,0),wins=samples.reduce((n,row)=>n+row.independentSuccesses,0);return <div key={mode} className="rounded-xl border p-4"><h3 className="font-semibold">{mode==="writing"?${JSON.stringify(en?"Writing":"Schreiben")}:${JSON.stringify(en?"Speaking":"Sprechen")}}</h3><p>{rows===null?"…":checked?\x60\x24{Math.round(wins/checked*100)}% · \x24{checked} ${en?"independent checks":"unabhängige Prüfungen"}\x60:${JSON.stringify(en?"Accuracy not yet established":"Genauigkeit noch nicht belegt")}}</p><p>{samples.reduce((n,row)=>n+row.attempts,0)} ${en?"saved attempts":"gespeicherte Versuche"}</p><p>{samples.reduce((n,row)=>n+row.delayedSuccesses,0)} ${en?"delayed successes":"erfolgreiche verzögerte Abrufe"}</p></div>;})}</div>{problem?<p role="status">{problem}</p>:null}<p className="mt-4 text-sm">${en?"These records do not certify a CEFR level. Retention and transfer need fresh, reviewed responses on later days.":"Diese Einträge bestätigen kein GER-Niveau. Behalten und Transfer benötigen neue, geprüfte Antworten an späteren Tagen."}</p><a className="mt-4 inline-block rounded-lg bg-blue-700 px-4 py-2 text-white" href="/practice">${en?"Continue independent practice":"Eigenständig weiterüben"}</a></section>;
}
`);
}
const enPath="Apps/English/English-Automaticity/apps/web/features/components/progress-insights.tsx";
let enText=readFileSync(enPath,"utf8");enText=enText.replace('import { Activity, Target }', 'import { AutomaticityEvidenceSummary } from "./automaticity-evidence-summary";\nimport { Activity, Target }');
enText=enText.replace('<div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]">','<AutomaticityEvidenceSummary />\n      <div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]">');
enText=enText.replaceAll('name: "Mastery"','name: "Legacy mastery estimate"').replaceAll('name: "Automaticity"','name: "Legacy fluency estimate"').replaceAll('Competency profile','Legacy practice profile').replaceAll('Content seen, securely learned, and used without help.','Historical practice estimates. They do not establish mastery or automaticity.').replaceAll('Overall profile','Practice estimate').replaceAll('Measurable learning progress','Learning activity and evidence');writeFileSync(enPath,enText);
const dePath="Apps/Deutsch-Automaticity/apps/web/src/features/progress/progress-evidence.tsx";
let deText=readFileSync(dePath,"utf8");deText=deText.replace('import {\n','import { AutomaticityEvidenceSummary } from "./automaticity-evidence-summary";\nimport {\n');deText=deText.replace('      <LearningAccordion','      <AutomaticityEvidenceSummary />\n      <LearningAccordion');
deText=deText.replace('mastery.status !== "new" &&\n      mastery.scores.speaking < 80','state.attempts.some(attempt => attempt.topic === mastery.topic && attempt.mode === "speaking" && attempt.verified === true) &&\n      mastery.status !== "new" &&\n      mastery.scores.speaking < 80');
deText=deText.replace('mastery.status !== "new" &&\n      mastery.scores.writing < 80','state.attempts.some(attempt => attempt.topic === mastery.topic && attempt.mode === "writing" && attempt.verified === true) &&\n      mastery.status !== "new" &&\n      mastery.scores.writing < 80');
deText=deText.replaceAll('Automatisierte Themen','Themen über der bisherigen Übungsschwelle').replaceAll('Automatisierungs-Aufbau','Übungsaufbau').replaceAll('5 Themen automatisieren','5 bisherige Übungsschwellen erreichen').replaceAll('label="Automatisiert"','label="Bisherige Übungsschwelle erreicht"').replaceAll('hint="Alle Nachweise erfüllt"','hint="Historischer App-Wert, kein Beherrschungsnachweis"').replaceAll('label="Instabil"','label="Weitere Übung vorgesehen"').replaceAll('hint="Noch nicht automatisch"','hint="Beherrschung unabhängig davon ungeprüft"').replaceAll('Status und Kompetenznachweise','Bisherige Übungswerte').replaceAll('Level-Freigabe','Übungsplan für das Niveau').replaceAll('Sprech-Nachweise','Geprüfte Sprechübungen').replaceAll('Schreib-Nachweise','Geprüfte Schreibübungen').replaceAll('Transfer-Nachweise','Geprüfte Transferübungen');writeFileSync(dePath,deText);
const labelPath="Apps/Deutsch-Automaticity/packages/domain/src/mastery.ts";let labels=readFileSync(labelPath,"utf8");labels=labels.replace('automatic: "Automatisiert"','automatic: "Übungsschwelle erreicht"');writeFileSync(labelPath,labels);
