import { resolve } from "node:path";
import { emitSevenStepFlow } from "../../../shared/seven-step-flow/build";
import { syncConversationFlow } from "../../../shared/conversation-flow/build";
import { worksheets as specialist } from "../packages/content/src/grammar-worksheets";
import { grammarUnits } from "../packages/content/src/index";
import { a1Worksheets } from "../packages/content/src/worksheet-seeds-a1";
import { germanSeeds } from "../../../shared/grammar-worksheets/seeds-de";
import {
  catalogWorksheets,
  emitSharedAssets,
} from "../../../shared/grammar-worksheets/build";
const worksheets = catalogWorksheets(
  grammarUnits,
  [...a1Worksheets, ...germanSeeds],
  "de",
  specialist,
);

const root = resolve(import.meta.dir, "..");
const out = resolve(root, "apps/web/public/replacements/de");
// The compatibility page loads classic scripts. Export explicitly to window rather
// than relying on a bundler-specific globalName option or a module loader.
await Bun.write(
  resolve(out, "grammar-worksheets.js"),
  `// Generated by scripts/build-grammar-worksheets.ts.\nwindow.GermanWorksheets = window.GrammarWorksheets = ${JSON.stringify({ worksheets })};\n`,
);

await emitSharedAssets(out);
await syncConversationFlow(root, "de");
await emitSevenStepFlow(root, "de");
console.log(
  `${worksheets.length} German worksheet sets verified against the catalog.`,
);
