import type { WorksheetSeed } from "./worksheet-seed";

const s = (
  topic: string,
  title: string,
  focusFa: string,
  chain: WorksheetSeed["chain"],
  category: string,
  examples: WorksheetSeed["examples"],
  change: string,
  personal: string,
  contextual = false,
): WorksheetSeed => ({
  level: "A1",
  topic,
  title,
  focusFa,
  chain,
  category,
  examples,
  change,
  personal,
  contextual,
});

// Each example supplies all grammar except the one span inside [[...]].
export const a1Worksheets: readonly WorksheetSeed[] = [
  s(
    "Personalpronomen und sein",
    "bin oder sind?",
    "فقط شکل فعل sein را با فاعل هماهنگ کن.",
    ["ich oder wir?", "Person und Zahl bestimmen", "ich bin / wir sind"],
    "Subjekt-Verb-Kongruenz",
    [
      ["ich", "Ich [[bin]] müde.", "sind"],
      ["wir", "Wir [[sind]] müde.", "bin"],
      ["ich", "Ich [[bin]] zu Hause.", "sind"],
      ["wir", "Wir [[sind]] zu Hause.", "bin"],
    ],
    "Ändere ich zu wir.",
    "Schreibe, wie du dich heute fühlst. Verwende ich bin.",
  ),
  s(
    "haben",
    "habe oder haben?",
    "فقط شکل haben را از روی فاعل انتخاب کن.",
    ["ich oder wir?", "Person und Zahl bestimmen", "ich habe / wir haben"],
    "Verbform",
    [
      ["ich", "Ich [[habe]] Zeit.", "haben"],
      ["wir", "Wir [[haben]] Zeit.", "habe"],
      ["ich", "Ich [[habe]] Hunger.", "haben"],
      ["wir", "Wir [[haben]] Hunger.", "habe"],
    ],
    "Ändere ich zu wir.",
    "Schreibe mit ich habe über Zeit, Hunger oder ein Hobby.",
  ),
  s(
    "Präsens regelmäßiger Verben",
    "-e oder -st?",
    "پایان فعل منظم را برای ich یا du انتخاب کن.",
    ["ich oder du?", "Präsensendung wählen", "ich lerne / du lernst"],
    "Präsensendung",
    [
      ["ich", "Ich [[lerne]] Deutsch.", "lernst"],
      ["du", "Du [[lernst]] Deutsch.", "lerne"],
      ["ich", "Ich [[wohne]] hier.", "wohnst"],
      ["du", "Du [[wohnst]] hier.", "wohne"],
    ],
    "Ändere ich zu du.",
    "Schreibe einen wahren Satz über dich mit lernen oder wohnen.",
  ),
  s(
    "Präsens unregelmäßiger Verben",
    "fahren: a oder ä?",
    "تغییر واکهٔ fahren را برای ich و du تشخیص بده.",
    ["fahren + ich/du", "du → Stammwechsel", "ich fahre / du fährst"],
    "Stammvokal",
    [
      ["ich", "Ich [[fahre]] nach Berlin.", "fähre"],
      ["du", "Du [[fährst]] nach Berlin.", "fahrst"],
      ["ich", "Ich [[fahre]] mit dem Bus.", "fähre"],
      ["du", "Du [[fährst]] mit dem Bus.", "fahrst"],
    ],
    "Ändere ich zu du.",
    "Schreibe mit ich fahre, wohin oder womit du oft fährst.",
  ),
  s(
    "W-Fragen",
    "Wo oder wohin?",
    "برای مکان از wo و برای مقصد از wohin استفاده کن.",
    ["Ort oder Ziel?", "Fragefunktion wählen", "Ort → wo / Ziel → wohin"],
    "Fragewort",
    [
      ["Wohnort erfragen", "[[Wo]] wohnst du?", "Wohin"],
      ["Ziel erfragen", "[[Wohin]] gehst du?", "Wo"],
      ["Aufenthaltsort erfragen", "[[Wo]] bist du?", "Wohin"],
      ["Reiseziel erfragen", "[[Wohin]] reist du?", "Wo"],
    ],
    "Frage mit gehst nach dem Ziel statt mit wohnst nach dem Wohnort.",
    "Schreibe eine Frage nach dem Wohnort einer Person.",
    true,
  ),
  s(
    "Ja/Nein-Fragen",
    "Das Verb nach vorn",
    "برای سؤال بله یا خیر فعل صرف‌شده را به آغاز ببر.",
    ["Ja/Nein-Frage?", "finites Verb vor das Subjekt", "Kommst du?"],
    "Verberststellung",
    [
      ["Frage mit kommen", "[[Kommst du]] heute?", "Du kommst"],
      ["Frage mit lernen", "[[Lernst du]] heute?", "Du lernst"],
      ["Frage mit arbeiten", "[[Arbeitest du]] morgen?", "Du arbeitest"],
      ["Frage mit bleiben", "[[Bleibst du]] hier?", "Du bleibst"],
    ],
    "Ersetze kommen durch lernen; bilde wieder eine Ja/Nein-Frage.",
    "Frage eine Person mit einer Ja/Nein-Frage nach ihrem morgigen Plan.",
    true,
  ),
  s(
    "bestimmter und unbestimmter Artikel",
    "ein oder der?",
    "در معرفی نخست ein و برای فرد شناخته‌شده der را انتخاب کن.",
    [
      "Referent neu oder bekannt?",
      "unbestimmt oder bestimmt",
      "ein Mann / der Mann",
    ],
    "Definitheit",
    [
      ["Ein Mann wird erstmals erwähnt", "Hier wartet [[ein]] Mann.", "der"],
      ["Der bereits genannte Mann", "Hier wartet [[der]] Mann.", "ein"],
      ["Ein Arzt wird erstmals erwähnt", "Hier arbeitet [[ein]] Arzt.", "der"],
      ["Der bereits genannte Arzt", "Hier arbeitet [[der]] Arzt.", "ein"],
    ],
    "Beziehe dich jetzt auf den bereits genannten Mann.",
    "Führe einen Gegenstand mit ein oder eine ein und erwähne ihn danach mit dem bestimmten Artikel.",
    true,
  ),
  s(
    "Pluralformen",
    "Kind oder Kinder?",
    "فقط جمعِ Kind و Buch را همراه با تعداد بساز.",
    ["eins oder mehrere?", "Pluralform abrufen", "Kinder / Bücher"],
    "Numerus",
    [
      ["zwei", "Hier spielen zwei [[Kinder]].", "Kind"],
      ["ein", "Hier spielt ein [[Kind]].", "Kinder"],
      ["drei", "Hier liegen drei [[Bücher]].", "Buch"],
      ["ein", "Hier liegt ein [[Buch]].", "Bücher"],
    ],
    "Ändere zwei zu ein; verwende die vorgegebene Verbform spielt.",
    "Schreibe mit einer Zahl, wie viele Bücher du auf deinem Tisch hast.",
  ),
  s(
    "Akkusativ",
    "der oder den?",
    "در مفعول مستقیم مذکر، den را انتخاب کن.",
    ["maskulines Nomen", "Subjekt oder direktes Objekt?", "der / den"],
    "Kasus des Artikels",
    [
      ["direktes Objekt", "Ich sehe [[den]] Mann.", "der"],
      ["Subjekt", "[[Der]] Mann sieht mich.", "Den"],
      ["direktes Objekt", "Ich höre [[den]] Lehrer.", "der"],
      ["Subjekt", "[[Der]] Lehrer hört mich.", "Den"],
    ],
    "Der Mann handelt jetzt selbst. Verwende sieht mich.",
    "Schreibe einen Satz mit ich sehe und einem männlichen Referenten.",
  ),
  s(
    "nicht und kein",
    "nicht oder kein?",
    "اسم بدون حرف تعریف را با kein و صفت را با nicht منفی کن.",
    [
      "Nomen ohne Artikel oder Adjektiv?",
      "Negationswort wählen",
      "kein Geld / nicht müde",
    ],
    "Negationswahl",
    [
      ["Nomen Geld verneinen", "Ich habe [[kein]] Geld.", "nicht"],
      ["Adjektiv müde verneinen", "Ich bin [[nicht]] müde.", "kein"],
      ["Nomen Zeit verneinen", "Ich habe [[keine]] Zeit.", "nicht"],
      ["Adjektiv krank verneinen", "Ich bin [[nicht]] krank.", "kein"],
    ],
    "Verneine jetzt mit ich bin das Adjektiv müde.",
    "Schreibe einen wahren negativen Satz mit nicht oder kein.",
  ),
  s(
    "Modalverb können",
    "können + Infinitiv",
    "پس از können شکل مصدر فعل را انتخاب کن.",
    [
      "können ist konjugiert",
      "zweites Verb bleibt Infinitiv",
      "kann schwimmen",
    ],
    "Infinitiv nach Modalverb",
    [
      ["kann", "Ich kann [[schwimmen]].", "schwimme"],
      ["ohne Modalverb", "Ich [[schwimme]].", "schwimmen"],
      ["kann", "Ich kann [[kochen]].", "koche"],
      ["ohne Modalverb", "Ich [[koche]].", "kochen"],
    ],
    "Entferne kann und konjugiere schwimmen für ich.",
    "Schreibe mit ich kann über eine Fähigkeit.",
  ),
  s(
    "Trennbare Verben",
    "anrufen: die Vorsilbe",
    "در جملهٔ اصلی پیشوند an را به پایان ببر.",
    ["anrufen im Hauptsatz", "Verb trennen", "rufe … an"],
    "Trennbare Vorsilbe",
    [
      ["anrufen, ich", "Ich rufe dich [[an]].", "auf"],
      ["aufstehen, ich", "Ich stehe früh [[auf]].", "an"],
      ["anrufen, wir", "Wir rufen morgen [[an]].", "auf"],
      ["aufstehen, wir", "Wir stehen früh [[auf]].", "an"],
    ],
    "Verwende jetzt aufstehen und früh: Ich stehe früh …",
    "Schreibe mit anrufen, wen du regelmäßig anrufst.",
    true,
  ),
  s(
    "lokale Präpositionen",
    "in oder bei?",
    "برای داخل یک مکان in و برای نزد یک شخص bei را انتخاب کن.",
    ["Innenraum oder Person?", "Ortspräposition wählen", "im Büro / bei Anna"],
    "Lokale Präposition",
    [
      ["Innenraum: Büro", "Ich bin [[im]] Büro.", "bei"],
      ["zu Besuch bei Anna", "Ich bin [[bei]] Anna.", "im"],
      ["Innenraum: Café", "Wir sind [[im]] Café.", "bei"],
      ["zu Besuch bei Paul", "Wir sind [[bei]] Paul.", "im"],
    ],
    "Beschreibe jetzt einen Besuch bei Anna statt den Aufenthalt im Büro.",
    "Schreibe, ob du gerade in einem Gebäude oder bei einer Person bist.",
  ),
  s(
    "Imperativ mit du, ihr und Sie",
    "Lies oder lest?",
    "صورت امر lesen را برای یک نفر یا چند نفر انتخاب کن.",
    ["du oder ihr?", "Adressatenzahl bestimmen", "lies / lest"],
    "Imperativform",
    [
      ["du", "[[Lies]] den Text!", "Lest"],
      ["ihr", "[[Lest]] den Text!", "Lies"],
      ["du", "[[Lies]] die Frage!", "Lest"],
      ["ihr", "[[Lest]] die Frage!", "Lies"],
    ],
    "Richte die Aufforderung an mehrere Personen mit ihr.",
    "Schreibe eine Aufforderung mit lesen an eine vertraute Person.",
    true,
  ),
  s(
    "Satzklammer im einfachen Hauptsatz",
    "Das Vollverb am Ende",
    "در جمله با wollen فعل اصلی را در پایان قرار بده.",
    ["wollen ist finit", "Vollverb ans Satzende", "will … lernen"],
    "Satzklammer",
    [
      [
        "Deutsch lernen",
        "Ich will [[heute Deutsch lernen]].",
        "lernen heute Deutsch",
      ],
      [
        "Deutsch sprechen",
        "Ich will [[heute Deutsch sprechen]].",
        "sprechen heute Deutsch",
      ],
      [
        "ein Buch lesen",
        "Ich will [[heute ein Buch lesen]].",
        "lesen heute ein Buch",
      ],
      ["Musik hören", "Ich will [[heute Musik hören]].", "hören heute Musik"],
    ],
    "Ersetze lernen durch sprechen; behalte heute Deutsch bei.",
    "Schreibe mit ich will über deinen heutigen Plan.",
  ),
  s(
    "Uhrzeit, Datum und Reihenfolge",
    "um bei Uhrzeiten",
    "برای ساعت دقیق از um استفاده کن.",
    ["Uhrzeit als Termin", "Präposition um", "um acht Uhr"],
    "Zeitpräposition",
    [
      ["Uhrzeit", "Der Kurs beginnt [[um]] acht Uhr.", "am"],
      ["Wochentag", "Der Kurs beginnt [[am]] Montag.", "um"],
      ["Uhrzeit", "Ich komme [[um]] neun Uhr.", "am"],
      ["Wochentag", "Ich komme [[am]] Dienstag.", "um"],
    ],
    "Ersetze acht Uhr durch Montag und wähle die passende Präposition.",
    "Schreibe mit um, wann du normalerweise aufstehst.",
  ),
  s(
    "Temporale Präpositionen am, um und im",
    "am oder im?",
    "برای روز am و برای ماه im را انتخاب کن.",
    ["Tag oder Monat?", "Zeitpräposition wählen", "am Montag / im Mai"],
    "Zeitpräposition",
    [
      ["Wochentag", "Ich komme [[am]] Montag.", "im"],
      ["Monat", "Ich komme [[im]] Mai.", "am"],
      ["Wochentag", "Der Kurs beginnt [[am]] Freitag.", "im"],
      ["Monat", "Der Kurs beginnt [[im]] Juni.", "am"],
    ],
    "Ersetze Montag durch Mai.",
    "Schreibe mit im, in welchem Monat du Geburtstag hast.",
  ),
  s(
    "Häufigkeitsadverbien",
    "oft oder nie?",
    "قید تکرار را با معنای موردنظر هماهنگ کن.",
    ["häufig oder kein einziges Mal?", "Häufigkeit ausdrücken", "oft / nie"],
    "Häufigkeitsbedeutung",
    [
      ["an vielen Tagen", "Ich koche [[oft]].", "nie"],
      ["kein einziges Mal", "Ich koche [[nie]].", "oft"],
      ["an vielen Tagen", "Ich lese [[oft]].", "nie"],
      ["kein einziges Mal", "Ich lese [[nie]].", "oft"],
    ],
    "Drücke jetzt aus, dass du kein einziges Mal kochst.",
    "Schreibe mit oft oder nie über eine Gewohnheit.",
    true,
  ),
  s(
    "es gibt mit Akkusativ",
    "es gibt + einen",
    "پس از es gibt برای اسم مذکر einen را انتخاب کن.",
    ["es gibt + maskulin", "Akkusativ", "einen Park"],
    "Akkusativ nach es gibt",
    [
      ["es gibt", "Hier gibt es [[einen]] Park.", "ein"],
      ["Subjekt", "Hier ist [[ein]] Park.", "einen"],
      ["es gibt", "Hier gibt es [[einen]] Bahnhof.", "ein"],
      ["Subjekt", "Hier ist [[ein]] Bahnhof.", "einen"],
    ],
    "Ersetze gibt es durch ist; der Park ist jetzt Subjekt.",
    "Schreibe, ob es in deiner Nähe einen Park oder einen Bahnhof gibt.",
  ),
  s(
    "man für allgemeine Aussagen",
    "man + dritte Person",
    "با man از فعل سوم‌شخص مفرد استفاده کن.",
    ["Subjekt man", "dritte Person Singular", "man lernt"],
    "Kongruenz mit man",
    [
      ["man", "Hier [[lernt]] man Deutsch.", "lernen"],
      ["wir", "Hier [[lernen]] wir Deutsch.", "lernt"],
      ["man", "Hier [[arbeitet]] man ruhig.", "arbeiten"],
      ["wir", "Hier [[arbeiten]] wir ruhig.", "arbeitet"],
    ],
    "Ersetze man durch wir.",
    "Schreibe mit man eine allgemeine Aussage über deinen Wohnort.",
  ),
  s(
    "und, aber, denn und oder",
    "Ergänzung oder Gegensatz?",
    "برای افزودن und و برای تضاد aber را انتخاب کن.",
    ["Ergänzung oder Gegensatz?", "Verknüpfung bestimmen", "und / aber"],
    "Konnektorbedeutung",
    [
      ["Ergänzung", "Ich lese [[und]] ich schreibe.", "aber"],
      ["Gegensatz", "Ich lese, [[aber]] ich schreibe nicht.", "und"],
      ["Ergänzung", "Ich lerne [[und]] ich übe.", "aber"],
      ["Gegensatz", "Ich lerne, [[aber]] ich übe nicht.", "und"],
    ],
    "Drücke einen Gegensatz aus: Der zweite Satz lautet ich schreibe nicht.",
    "Verbinde zwei wahre Aussagen über deinen Alltag mit und oder aber.",
    true,
  ),
  s(
    "Mengenwörter viel, wenig und genug",
    "viel oder viele?",
    "برای اسم غیرقابل‌شمارش viel و برای جمع viele را انتخاب کن.",
    [
      "nicht zählbar oder Plural?",
      "Mengenwort anpassen",
      "viel Wasser / viele Bücher",
    ],
    "Zählbarkeit",
    [
      ["Wasser: nicht zählbar", "Ich habe [[viel]] Wasser.", "viele"],
      ["Bücher: Plural", "Ich habe [[viele]] Bücher.", "viel"],
      ["Zeit: nicht zählbar", "Ich habe [[viel]] Zeit.", "viele"],
      ["Termine: Plural", "Ich habe [[viele]] Termine.", "viel"],
    ],
    "Ersetze Wasser durch Bücher.",
    "Schreibe mit viel oder viele über etwas, das du hast.",
  ),
  s(
    "Akkusativpronomen",
    "ihn oder sie?",
    "ضمیر مفعولی را با مرجع مذکر یا مؤنث هماهنگ کن.",
    ["sehen + Referent", "Akkusativpronomen wählen", "Paul → ihn / Anna → sie"],
    "Pronomenbezug im Akkusativ",
    [
      ["Paul", "Ich sehe [[ihn]].", "ihm"],
      ["Anna", "Ich sehe [[sie]].", "ihr"],
      ["Paul", "Ich besuche [[ihn]].", "ihm"],
      ["Anna", "Ich besuche [[sie]].", "ihr"],
    ],
    "Ersetze den Bezug Paul durch Anna.",
    "Nenne eine Person und schreibe danach mit ich sehe ihn oder sie über sie.",
  ),
];
