export const words = {
  prepare: ["Prepare", "Vorbereiten", "آماده‌سازی"],
  speak: ["Speak", "Sprechen", "گفتار"],
  feedback: ["Feedback", "Rückmeldung", "بازخورد"],
  home: ["Back to learning", "Zurück zum Lernen", "بازگشت به یادگیری"],
  choose: ["Choose a topic", "Thema auswählen", "انتخاب موضوع"],
  level: ["Level", "Niveau", "سطح"],
  all: ["All", "Alle", "همه"],
  task: ["Your task", "Deine Aufgabe", "تکلیف تو"],
  example: ["Listen to an example", "Beispiel anhören", "شنیدن نمونه"],
  noExample: [
    "No teacher recording is attached to this topic yet.",
    "Für dieses Thema gibt es noch keine Aufnahme der Lehrkraft.",
    "هنوز نمونهٔ صوتی مدرس برای این موضوع ثبت نشده است.",
  ],
  hints: [
    "Helpful phrases · optional",
    "Hilfreiche Wendungen · optional",
    "عبارت‌های کمکی · اختیاری",
  ],
  continue: [
    "Continue to speaking",
    "Weiter zum Sprechen",
    "ادامه و شروع گفتار",
  ],
  instructions: ["Instructions", "Anleitung", "زبان راهنما"],
  showTask: ["Show task", "Aufgabe anzeigen", "نمایش تکلیف"],
  showHints: ["Show phrases", "Wendungen anzeigen", "نمایش عبارت‌ها"],
  record: ["Start recording", "Aufnahme starten", "شروع ضبط"],
  pause: ["Pause", "Pausieren", "مکث"],
  resume: ["Resume", "Fortsetzen", "ادامهٔ ضبط"],
  stop: ["Finish recording", "Aufnahme beenden", "پایان ضبط"],
  ready: [
    "Ready when you are",
    "Bereit, wenn du es bist",
    "هر وقت آماده‌ای شروع کن",
  ],
  recording: ["Recording", "Aufnahme läuft", "در حال ضبط"],
  paused: ["Paused", "Pausiert", "ضبط در مکث است"],
  requesting: [
    "Waiting for microphone permission",
    "Warten auf die Mikrofonfreigabe",
    "در انتظار اجازهٔ میکروفون",
  ],
  silence: [
    "No sound detected yet. Speak when you are ready.",
    "Noch kein Ton erkannt. Sprich, wenn du bereit bist.",
    "هنوز صدایی دریافت نشده؛ هر وقت آماده‌ای صحبت کن.",
  ],
  interrupted: [
    "Recording paused or interrupted. Your saved draft is kept.",
    "Aufnahme pausiert oder unterbrochen. Dein gespeicherter Entwurf bleibt erhalten.",
    "ضبط مکث یا قطع شده است. پیش‌نویس ذخیره‌شده حفظ می‌شود.",
  ],
  blocked: [
    "Microphone access is blocked. Check this site's permissions and secure connection.",
    "Der Mikrofonzugriff ist gesperrt. Prüfe die Website-Berechtigung und die sichere Verbindung.",
    "دسترسی میکروفون مسدود است. اجازهٔ سایت و اتصال امن را بررسی کن.",
  ],
  missing: [
    "No suitable microphone was found. Connect or select an input device.",
    "Kein passendes Mikrofon gefunden. Verbinde oder wähle ein Eingabegerät.",
    "میکروفون مناسب پیدا نشد. یک دستگاه ورودی وصل یا انتخاب کن.",
  ],
  device: [
    "The microphone cannot be read. Check the device or other apps using it.",
    "Das Mikrofon ist nicht lesbar. Prüfe das Gerät und andere Audio-Apps.",
    "میکروفون قابل استفاده نیست. دستگاه و برنامه‌های صوتی دیگر را بررسی کن.",
  ],
  unsupported: [
    "Recording requires a supported browser and HTTPS or localhost.",
    "Die Aufnahme benötigt einen unterstützten Browser und HTTPS oder localhost.",
    "ضبط به مرورگر پشتیبانی‌شده و HTTPS یا localhost نیاز دارد.",
  ],
  asr: [
    "Live transcription is unavailable. Replay your audio and type what you said.",
    "Keine Live-Transkription verfügbar. Höre die Aufnahme an und schreibe auf, was du gesagt hast.",
    "رونویسی زنده در دسترس نیست. صدا را بشنو و آنچه گفته‌ای بنویس.",
  ],
  local: [
    "Audio drafts stay on this device. Browser transcription may use your browser's speech service.",
    "Audioentwürfe bleiben auf diesem Gerät. Die Transkription kann den Sprachdienst deines Browsers verwenden.",
    "پیش‌نویس صوتی در این دستگاه می‌ماند. رونویسی ممکن است از سرویس گفتار مرورگر استفاده کند.",
  ],
  transcript: ["Check your transcript", "Transkript prüfen", "بررسی رونویسی"],
  transcriptHelp: [
    "Replay the audio. Fix recognition errors before requesting feedback.",
    "Höre die Aufnahme an. Berichtige Erkennungsfehler, bevor du Rückmeldung anforderst.",
    "صدا را دوباره بشنو. پیش از درخواست بازخورد، خطاهای رونویسی را اصلاح کن.",
  ],
  confirm: ["Confirm transcript", "Transkript bestätigen", "تأیید رونویسی"],
  confirmed: [
    "Transcript confirmed",
    "Transkript bestätigt",
    "رونویسی تأیید شد",
  ],
  evaluate: [
    "Get grammar feedback",
    "Grammatik prüfen lassen",
    "دریافت بازخورد گرامر",
  ],
  evaluating: ["Checking…", "Wird geprüft…", "در حال بررسی…"],
  provider: [
    "Grammar feedback is unavailable. Your recording and draft are still saved; try again later.",
    "Grammatikprüfung nicht verfügbar. Aufnahme und Entwurf bleiben gespeichert; versuche es später erneut.",
    "بازخورد گرامر در دسترس نیست. ضبط و پیش‌نویس حفظ می‌شوند؛ بعداً دوباره تلاش کن.",
  ],
  focus: [
    "One correction to practise",
    "Eine Korrektur zum Üben",
    "یک اصلاح برای تمرین",
  ],
  original: ["Confirmed text", "Bestätigter Text", "متن تأییدشده"],
  better: ["Suggested form", "Vorgeschlagene Form", "صورت پیشنهادی"],
  why: ["Why?", "Warum?", "چرا؟"],
  contrast: ["Your contrasting example", "Dein Gegenbeispiel", "مثال متضاد تو"],
  noIssues: [
    "No issue was returned for this text. This does not assess pronunciation or prove mastery.",
    "Für diesen Text wurde kein Fehler gemeldet. Das bewertet weder Aussprache noch sichere Beherrschung.",
    "برای این متن خطایی گزارش نشد. این نتیجه ارزیابی تلفظ یا اثبات تسلط نیست.",
  ],
  more: ["More corrections", "Weitere Korrekturen", "اصلاح‌های بیشتر"],
  retry: ["Try again", "Noch einmal sprechen", "دوباره صحبت کن"],
  immediate: [
    "Immediate practice · same task",
    "Direkte Wiederholung · gleiche Aufgabe",
    "تمرین فوری · همان تکلیف",
  ],
  saveLater: [
    "Save and continue later",
    "Speichern und später fortsetzen",
    "ذخیره و ادامه در زمان دیگر",
  ],
  saved: [
    "Draft saved on this device",
    "Entwurf auf diesem Gerät gespeichert",
    "پیش‌نویس در این دستگاه ذخیره شد",
  ],
  saving: [
    "Saving draft…",
    "Entwurf wird gespeichert…",
    "در حال ذخیرهٔ پیش‌نویس…",
  ],
  saveFailed: [
    "Draft could not be saved. Keep this page open and download the recording.",
    "Entwurf konnte nicht gespeichert werden. Lass diese Seite offen und lade die Aufnahme herunter.",
    "پیش‌نویس ذخیره نشد. صفحه را باز نگه دار و فایل ضبط را دانلود کن.",
  ],
  download: ["Download recording", "Aufnahme herunterladen", "دانلود ضبط"],
  finish: [
    "Finish this practice",
    "Diese Übung abschließen",
    "پایان این تمرین",
  ],
  complete: ["Practice completed", "Übung abgeschlossen", "تمرین تکمیل شد"],
  review: [
    "Schedule a fresh task",
    "Neue Aufgabe zur Wiederholung planen",
    "زمان‌بندی تکلیف تازه",
  ],
  day: ["Day", "Tag", "روز"],
  scheduled: ["Review scheduled", "Wiederholung geplant", "مرور زمان‌بندی شد"],
  startReview: ["Start review", "Wiederholung starten", "شروع مرور"],
  due: ["Available on", "Verfügbar am", "قابل انجام در"],
  library: [
    "Saved drafts and reviews",
    "Gespeicherte Entwürfe und Wiederholungen",
    "پیش‌نویس‌ها و مرورهای ذخیره‌شده",
  ],
  open: ["Resume draft", "Entwurf fortsetzen", "ادامهٔ پیش‌نویس"],
  attempt: ["Attempt", "Versuch", "تلاش"],
  measurements: ["Recording details", "Aufnahmedetails", "جزئیات ضبط"],
  raw: [
    "Original automatic transcript",
    "Ursprüngliches automatisches Transkript",
    "رونویسی خودکار اولیه",
  ],
  words: ["ASR words", "ASR-Wörter", "واژه‌های رونویسی خودکار"],
  wpm: [
    "Estimated words/minute",
    "Geschätzte Wörter/Minute",
    "واژه در دقیقه · تخمینی",
  ],
  measurementHelp: [
    "Based on original recognition and recording time, excluding manual pauses. Edited text and playback speed do not change these estimates.",
    "Aus ursprünglicher Erkennung und Aufnahmezeit, ohne manuelle Pausen. Textänderungen und Abspieltempo verändern diese Schätzung nicht.",
    "بر پایهٔ رونویسی اولیه و زمان ضبط، بدون مکث دستی. ویرایش متن و سرعت پخش این تخمین را تغییر نمی‌دهند.",
  ],
  pronunciation: [
    "Pronunciation: not assessed",
    "Aussprache: nicht bewertet",
    "تلفظ: ارزیابی نشده",
  ],
  errorLog: ["My error note", "Meine Fehlernotiz", "یادداشت خطای من"],
  mode: ["Activity", "Übungsform", "نوع فعالیت"],
  monologue: ["Speaking task", "Sprechaufgabe", "تکلیف گفتاری"],
  dialogue: ["Guided exchange", "Geführter Austausch", "گفت‌وگوی هدایت‌شده"],
  partner: [
    "Listen to your partner",
    "Höre deinem Gegenüber zu",
    "به طرف مقابل گوش بده",
  ],
  partnerLabel: [
    "Device voice · fixed practice partner",
    "Gerätestimme · fester Übungspartner",
    "صدای دستگاه · طرف گفت‌وگوی تمرینی ثابت",
  ],
  nextTurn: [
    "Hear the follow-up question",
    "Rückfrage anhören",
    "شنیدن پرسش پیگیری",
  ],
  noVoice: [
    "No suitable device voice is available. Read the partner's question instead.",
    "Keine passende Gerätestimme verfügbar. Lies stattdessen die Frage.",
    "صدای مناسب دستگاه در دسترس نیست. پرسش طرف مقابل را بخوان.",
  ],
  comparison: [
    "Attempts are kept separately. A retry practises the same task; it does not certify transfer or automaticity.",
    "Versuche bleiben getrennt. Eine Wiederholung übt dieselbe Aufgabe; sie belegt weder Transfer noch Automatisierung.",
    "تلاش‌ها جدا حفظ می‌شوند. تکرار همان تکلیف، اثبات انتقال یا خودکارشدن نیست.",
  ],
  back: ["Back", "Zurück", "بازگشت"],
  empty: [
    "No saved recordings yet",
    "Noch keine gespeicherten Aufnahmen",
    "هنوز ضبطی ذخیره نشده است",
  ],
} as const;
export type CopyKey = keyof typeof words;
