"use client";
import {useEffect,useState} from "react";
import {readAutomaticityEvents,reduceAutomaticityEvents,type ConstructionProgress} from "@automaticity/learning-core/automaticity";
export function AutomaticityEvidenceSummary(){
  const [rows,setRows]=useState<ConstructionProgress[]|null>(null);
  const [problem,setProblem]=useState("");
  useEffect(()=>{const refresh=()=>{try{const read=readAutomaticityEvents(localStorage,"en");const reduced=reduceAutomaticityEvents(read.events,"en",new Date().toISOString());setRows(reduced.progress);if(read.unreadable.length||reduced.rejected.length)setProblem("Some records could not be verified. They remain in your complete backup.");}catch{setProblem("Saved evidence is unavailable.");}};refresh();window.addEventListener("storage",refresh);return()=>window.removeEventListener("storage",refresh);},[]);
  return <section className="rounded-2xl border border-blue-200 bg-white p-5" aria-label="Independent learning evidence"><h2 className="text-xl font-bold">Evidence from your own responses</h2><p className="my-3 text-sm">Hints, model answers and repeated repairs remain practice. Unknown skills need a suitable review before they receive an accuracy score.</p><div className="grid gap-4 sm:grid-cols-2">{(["writing","speaking"] as const).map(mode=>{const samples=(rows??[]).filter(row=>row.modality===mode);const checked=samples.reduce((n,row)=>n+row.independentAssessed,0),wins=samples.reduce((n,row)=>n+row.independentSuccesses,0);return <div key={mode} className="rounded-xl border p-4"><h3 className="font-semibold">{mode==="writing"?"Writing":"Speaking"}</h3><p>{rows===null?"…":checked?`${Math.round(wins/checked*100)}% · ${checked} independent checks`:"Accuracy not yet established"}</p><p>{samples.reduce((n,row)=>n+row.attempts,0)} saved attempts</p><p>{samples.reduce((n,row)=>n+row.delayedSuccesses,0)} delayed successes</p></div>;})}</div>{problem?<p role="status">{problem}</p>:null}<p className="mt-4 text-sm">These records do not certify a CEFR level. Retention and transfer need fresh, reviewed responses on later days.</p><a className="mt-4 inline-block rounded-lg bg-blue-700 px-4 py-2 text-white" href="/practice">Continue independent practice</a></section>;
}
